// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: databaseVariables.proto

#include "databaseVariables.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_common_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_MarkedMultiReference_common_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_common_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_MetaData_common_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_databaseVariables_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_DatabaseVariables_VariablesEntry_DoNotUse_databaseVariables_2eproto;
namespace com {
namespace alipay {
namespace dds {
namespace api {
namespace v1 {
class DatabaseVariables_VariablesEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DatabaseVariables_VariablesEntry_DoNotUse> _instance;
} _DatabaseVariables_VariablesEntry_DoNotUse_default_instance_;
class DatabaseVariablesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DatabaseVariables> _instance;
} _DatabaseVariables_default_instance_;
}  // namespace v1
}  // namespace api
}  // namespace dds
}  // namespace alipay
}  // namespace com
static void InitDefaultsDatabaseVariables_VariablesEntry_DoNotUse_databaseVariables_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::alipay::dds::api::v1::_DatabaseVariables_VariablesEntry_DoNotUse_default_instance_;
    new (ptr) ::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse();
  }
  ::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DatabaseVariables_VariablesEntry_DoNotUse_databaseVariables_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDatabaseVariables_VariablesEntry_DoNotUse_databaseVariables_2eproto}, {}};

static void InitDefaultsDatabaseVariables_databaseVariables_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::alipay::dds::api::v1::_DatabaseVariables_default_instance_;
    new (ptr) ::com::alipay::dds::api::v1::DatabaseVariables();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::alipay::dds::api::v1::DatabaseVariables::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_DatabaseVariables_databaseVariables_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsDatabaseVariables_databaseVariables_2eproto}, {
      &scc_info_MetaData_common_2eproto.base,
      &scc_info_DatabaseVariables_VariablesEntry_DoNotUse_databaseVariables_2eproto.base,
      &scc_info_MarkedMultiReference_common_2eproto.base,}};

void InitDefaults_databaseVariables_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_DatabaseVariables_VariablesEntry_DoNotUse_databaseVariables_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DatabaseVariables_databaseVariables_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_databaseVariables_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_databaseVariables_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_databaseVariables_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_databaseVariables_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseVariables, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseVariables, metadata_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseVariables, variables_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseVariables, extension_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse)},
  { 9, -1, sizeof(::com::alipay::dds::api::v1::DatabaseVariables)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::alipay::dds::api::v1::_DatabaseVariables_VariablesEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::alipay::dds::api::v1::_DatabaseVariables_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_databaseVariables_2eproto = {
  {}, AddDescriptors_databaseVariables_2eproto, "databaseVariables.proto", schemas,
  file_default_instances, TableStruct_databaseVariables_2eproto::offsets,
  file_level_metadata_databaseVariables_2eproto, 2, file_level_enum_descriptors_databaseVariables_2eproto, file_level_service_descriptors_databaseVariables_2eproto,
};

const char descriptor_table_protodef_databaseVariables_2eproto[] =
  "\n\027databaseVariables.proto\022\025com.alipay.dd"
  "s.api.v1\032\014common.proto\"\204\002\n\021DatabaseVaria"
  "bles\0221\n\010metadata\030\001 \001(\0132\037.com.alipay.dds."
  "api.v1.MetaData\022J\n\tvariables\030\002 \003(\01327.com"
  ".alipay.dds.api.v1.DatabaseVariables.Var"
  "iablesEntry\022>\n\textension\030\003 \003(\0132+.com.ali"
  "pay.dds.api.v1.MarkedMultiReference\0320\n\016V"
  "ariablesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001("
  "\t:\0028\001B=\n\025com.alipay.dds.api.v1B\026Database"
  "VariablesProtoP\000Z\ndds/api/v1b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_databaseVariables_2eproto = {
  false, InitDefaults_databaseVariables_2eproto, 
  descriptor_table_protodef_databaseVariables_2eproto,
  "databaseVariables.proto", &assign_descriptors_table_databaseVariables_2eproto, 396,
};

void AddDescriptors_databaseVariables_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_common_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_databaseVariables_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_databaseVariables_2eproto = []() { AddDescriptors_databaseVariables_2eproto(); return true; }();
namespace com {
namespace alipay {
namespace dds {
namespace api {
namespace v1 {

// ===================================================================

DatabaseVariables_VariablesEntry_DoNotUse::DatabaseVariables_VariablesEntry_DoNotUse() {}
DatabaseVariables_VariablesEntry_DoNotUse::DatabaseVariables_VariablesEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
void DatabaseVariables_VariablesEntry_DoNotUse::MergeFrom(const DatabaseVariables_VariablesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata DatabaseVariables_VariablesEntry_DoNotUse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_databaseVariables_2eproto);
  return ::file_level_metadata_databaseVariables_2eproto[0];
}
void DatabaseVariables_VariablesEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DatabaseVariables_VariablesEntry_DoNotUse::_ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx) {
  using MF = ::google::protobuf::internal::MapField<
      DatabaseVariables_VariablesEntry_DoNotUse, EntryKeyType, EntryValueType,
      kEntryKeyFieldType, kEntryValueFieldType,
      kEntryDefaultEnumValue>;
  auto mf = static_cast<MF*>(object);
  Parser<MF, ::google::protobuf::Map<EntryKeyType, EntryValueType>> parser(mf);
#define DO_(x) if (!(x)) return false
  DO_(parser.ParseMap(begin, end));
  DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
    parser.key().data(), static_cast<int>(parser.key().length()),
    ::google::protobuf::internal::WireFormatLite::PARSE,
    "com.alipay.dds.api.v1.DatabaseVariables.VariablesEntry.key"));
  DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
    parser.value().data(), static_cast<int>(parser.value().length()),
    ::google::protobuf::internal::WireFormatLite::PARSE,
    "com.alipay.dds.api.v1.DatabaseVariables.VariablesEntry.value"));
#undef DO_
  return true;
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER


// ===================================================================

void DatabaseVariables::InitAsDefaultInstance() {
  ::com::alipay::dds::api::v1::_DatabaseVariables_default_instance_._instance.get_mutable()->metadata_ = const_cast< ::com::alipay::dds::api::v1::MetaData*>(
      ::com::alipay::dds::api::v1::MetaData::internal_default_instance());
}
class DatabaseVariables::HasBitSetters {
 public:
  static const ::com::alipay::dds::api::v1::MetaData& metadata(const DatabaseVariables* msg);
};

const ::com::alipay::dds::api::v1::MetaData&
DatabaseVariables::HasBitSetters::metadata(const DatabaseVariables* msg) {
  return *msg->metadata_;
}
void DatabaseVariables::clear_metadata() {
  if (GetArenaNoVirtual() == nullptr && metadata_ != nullptr) {
    delete metadata_;
  }
  metadata_ = nullptr;
}
void DatabaseVariables::clear_extension() {
  extension_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DatabaseVariables::kMetadataFieldNumber;
const int DatabaseVariables::kVariablesFieldNumber;
const int DatabaseVariables::kExtensionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DatabaseVariables::DatabaseVariables()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.alipay.dds.api.v1.DatabaseVariables)
}
DatabaseVariables::DatabaseVariables(const DatabaseVariables& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      extension_(from.extension_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  variables_.MergeFrom(from.variables_);
  if (from.has_metadata()) {
    metadata_ = new ::com::alipay::dds::api::v1::MetaData(*from.metadata_);
  } else {
    metadata_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:com.alipay.dds.api.v1.DatabaseVariables)
}

void DatabaseVariables::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_DatabaseVariables_databaseVariables_2eproto.base);
  metadata_ = nullptr;
}

DatabaseVariables::~DatabaseVariables() {
  // @@protoc_insertion_point(destructor:com.alipay.dds.api.v1.DatabaseVariables)
  SharedDtor();
}

void DatabaseVariables::SharedDtor() {
  if (this != internal_default_instance()) delete metadata_;
}

void DatabaseVariables::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DatabaseVariables& DatabaseVariables::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_DatabaseVariables_databaseVariables_2eproto.base);
  return *internal_default_instance();
}


void DatabaseVariables::Clear() {
// @@protoc_insertion_point(message_clear_start:com.alipay.dds.api.v1.DatabaseVariables)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  variables_.Clear();
  extension_.Clear();
  if (GetArenaNoVirtual() == nullptr && metadata_ != nullptr) {
    delete metadata_;
  }
  metadata_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DatabaseVariables::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<DatabaseVariables*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .com.alipay.dds.api.v1.MetaData metadata = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::com::alipay::dds::api::v1::MetaData::_InternalParse;
        object = msg->mutable_metadata();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // map<string, string> variables = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::SlowMapEntryParser;
          auto parse_map = ::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse::_ParseMap;
          ctx->extra_parse_data().payload.clear();
          ctx->extra_parse_data().parse_map = parse_map;
          object = &msg->variables_;
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(parse_map(ptr, newend, object, ctx));
          ptr = newend;
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 18 && (ptr += 1));
        break;
      }
      // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::com::alipay::dds::api::v1::MarkedMultiReference::_InternalParse;
          object = msg->add_extension();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 26 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DatabaseVariables::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.alipay.dds.api.v1.DatabaseVariables)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .com.alipay.dds.api.v1.MetaData metadata = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_metadata()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> variables = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DatabaseVariables_VariablesEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              DatabaseVariables_VariablesEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&variables_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseVariables.VariablesEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseVariables.VariablesEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_extension()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.alipay.dds.api.v1.DatabaseVariables)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.alipay.dds.api.v1.DatabaseVariables)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DatabaseVariables::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.alipay.dds.api.v1.DatabaseVariables)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.alipay.dds.api.v1.MetaData metadata = 1;
  if (this->has_metadata()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::metadata(this), output);
  }

  // map<string, string> variables = 2;
  if (!this->variables().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "com.alipay.dds.api.v1.DatabaseVariables.VariablesEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "com.alipay.dds.api.v1.DatabaseVariables.VariablesEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->variables().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->variables().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->variables().begin();
          it != this->variables().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<DatabaseVariables_VariablesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(variables_.NewEntryWrapper(items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(2, *entry, output);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      ::std::unique_ptr<DatabaseVariables_VariablesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->variables().begin();
          it != this->variables().end(); ++it) {
        entry.reset(variables_.NewEntryWrapper(it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(2, *entry, output);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->extension_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->extension(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.alipay.dds.api.v1.DatabaseVariables)
}

::google::protobuf::uint8* DatabaseVariables::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.alipay.dds.api.v1.DatabaseVariables)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.alipay.dds.api.v1.MetaData metadata = 1;
  if (this->has_metadata()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::metadata(this), target);
  }

  // map<string, string> variables = 2;
  if (!this->variables().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "com.alipay.dds.api.v1.DatabaseVariables.VariablesEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "com.alipay.dds.api.v1.DatabaseVariables.VariablesEntry.value");
      }
    };

    if (false &&
        this->variables().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->variables().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->variables().begin();
          it != this->variables().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<DatabaseVariables_VariablesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(variables_.NewEntryWrapper(items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageNoVirtualToArray(2, *entry, target);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      ::std::unique_ptr<DatabaseVariables_VariablesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->variables().begin();
          it != this->variables().end(); ++it) {
        entry.reset(variables_.NewEntryWrapper(it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageNoVirtualToArray(2, *entry, target);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->extension_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->extension(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.alipay.dds.api.v1.DatabaseVariables)
  return target;
}

size_t DatabaseVariables::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.alipay.dds.api.v1.DatabaseVariables)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> variables = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->variables_size());
  {
    ::std::unique_ptr<DatabaseVariables_VariablesEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->variables().begin();
        it != this->variables().end(); ++it) {
      entry.reset(variables_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->extension_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->extension(static_cast<int>(i)));
    }
  }

  // .com.alipay.dds.api.v1.MetaData metadata = 1;
  if (this->has_metadata()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *metadata_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DatabaseVariables::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.alipay.dds.api.v1.DatabaseVariables)
  GOOGLE_DCHECK_NE(&from, this);
  const DatabaseVariables* source =
      ::google::protobuf::DynamicCastToGenerated<DatabaseVariables>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.alipay.dds.api.v1.DatabaseVariables)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.alipay.dds.api.v1.DatabaseVariables)
    MergeFrom(*source);
  }
}

void DatabaseVariables::MergeFrom(const DatabaseVariables& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.alipay.dds.api.v1.DatabaseVariables)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  variables_.MergeFrom(from.variables_);
  extension_.MergeFrom(from.extension_);
  if (from.has_metadata()) {
    mutable_metadata()->::com::alipay::dds::api::v1::MetaData::MergeFrom(from.metadata());
  }
}

void DatabaseVariables::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.alipay.dds.api.v1.DatabaseVariables)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DatabaseVariables::CopyFrom(const DatabaseVariables& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.alipay.dds.api.v1.DatabaseVariables)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DatabaseVariables::IsInitialized() const {
  return true;
}

void DatabaseVariables::Swap(DatabaseVariables* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DatabaseVariables::InternalSwap(DatabaseVariables* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  variables_.Swap(&other->variables_);
  CastToBase(&extension_)->InternalSwap(CastToBase(&other->extension_));
  swap(metadata_, other->metadata_);
}

::google::protobuf::Metadata DatabaseVariables::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_databaseVariables_2eproto);
  return ::file_level_metadata_databaseVariables_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
}  // namespace dds
}  // namespace alipay
}  // namespace com
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse* Arena::CreateMaybeMessage< ::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::com::alipay::dds::api::v1::DatabaseVariables_VariablesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::com::alipay::dds::api::v1::DatabaseVariables* Arena::CreateMaybeMessage< ::com::alipay::dds::api::v1::DatabaseVariables >(Arena* arena) {
  return Arena::CreateInternal< ::com::alipay::dds::api::v1::DatabaseVariables >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
