// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: databaseAuthorities.proto

#include "databaseAuthorities.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_common_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_MarkedMultiReference_common_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_common_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_MetaData_common_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_databaseAuthorities_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_DatabaseAuthorities_VariablesEntry_DoNotUse_databaseAuthorities_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_databaseAuthorities_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_DatabaseUser_databaseAuthorities_2eproto;
namespace com {
namespace alipay {
namespace dds {
namespace api {
namespace v1 {
class DatabaseAuthorities_VariablesEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DatabaseAuthorities_VariablesEntry_DoNotUse> _instance;
} _DatabaseAuthorities_VariablesEntry_DoNotUse_default_instance_;
class DatabaseAuthoritiesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DatabaseAuthorities> _instance;
} _DatabaseAuthorities_default_instance_;
class DatabaseUserDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DatabaseUser> _instance;
} _DatabaseUser_default_instance_;
}  // namespace v1
}  // namespace api
}  // namespace dds
}  // namespace alipay
}  // namespace com
static void InitDefaultsDatabaseAuthorities_VariablesEntry_DoNotUse_databaseAuthorities_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::alipay::dds::api::v1::_DatabaseAuthorities_VariablesEntry_DoNotUse_default_instance_;
    new (ptr) ::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse();
  }
  ::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DatabaseAuthorities_VariablesEntry_DoNotUse_databaseAuthorities_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDatabaseAuthorities_VariablesEntry_DoNotUse_databaseAuthorities_2eproto}, {}};

static void InitDefaultsDatabaseAuthorities_databaseAuthorities_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::alipay::dds::api::v1::_DatabaseAuthorities_default_instance_;
    new (ptr) ::com::alipay::dds::api::v1::DatabaseAuthorities();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::alipay::dds::api::v1::DatabaseAuthorities::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<4> scc_info_DatabaseAuthorities_databaseAuthorities_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 4, InitDefaultsDatabaseAuthorities_databaseAuthorities_2eproto}, {
      &scc_info_MetaData_common_2eproto.base,
      &scc_info_DatabaseUser_databaseAuthorities_2eproto.base,
      &scc_info_DatabaseAuthorities_VariablesEntry_DoNotUse_databaseAuthorities_2eproto.base,
      &scc_info_MarkedMultiReference_common_2eproto.base,}};

static void InitDefaultsDatabaseUser_databaseAuthorities_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::alipay::dds::api::v1::_DatabaseUser_default_instance_;
    new (ptr) ::com::alipay::dds::api::v1::DatabaseUser();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::alipay::dds::api::v1::DatabaseUser::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DatabaseUser_databaseAuthorities_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDatabaseUser_databaseAuthorities_2eproto}, {}};

void InitDefaults_databaseAuthorities_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_DatabaseAuthorities_VariablesEntry_DoNotUse_databaseAuthorities_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DatabaseAuthorities_databaseAuthorities_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DatabaseUser_databaseAuthorities_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_databaseAuthorities_2eproto[3];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_databaseAuthorities_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_databaseAuthorities_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_databaseAuthorities_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities, metadata_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities, users_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities, variables_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseAuthorities, extension_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, user_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, host_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, password_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, select_priv_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, insert_priv_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, update_priv_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, delete_priv_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, create_priv_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, drop_priv_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, index_priv_),
  PROTOBUF_FIELD_OFFSET(::com::alipay::dds::api::v1::DatabaseUser, alter_priv_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse)},
  { 9, -1, sizeof(::com::alipay::dds::api::v1::DatabaseAuthorities)},
  { 18, -1, sizeof(::com::alipay::dds::api::v1::DatabaseUser)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::alipay::dds::api::v1::_DatabaseAuthorities_VariablesEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::alipay::dds::api::v1::_DatabaseAuthorities_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::alipay::dds::api::v1::_DatabaseUser_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_databaseAuthorities_2eproto = {
  {}, AddDescriptors_databaseAuthorities_2eproto, "databaseAuthorities.proto", schemas,
  file_default_instances, TableStruct_databaseAuthorities_2eproto::offsets,
  file_level_metadata_databaseAuthorities_2eproto, 3, file_level_enum_descriptors_databaseAuthorities_2eproto, file_level_service_descriptors_databaseAuthorities_2eproto,
};

const char descriptor_table_protodef_databaseAuthorities_2eproto[] =
  "\n\031databaseAuthorities.proto\022\025com.alipay."
  "dds.api.v1\032\014common.proto\"\274\002\n\023DatabaseAut"
  "horities\0221\n\010metadata\030\001 \001(\0132\037.com.alipay."
  "dds.api.v1.MetaData\0222\n\005users\030\002 \003(\0132#.com"
  ".alipay.dds.api.v1.DatabaseUser\022L\n\tvaria"
  "bles\030\003 \003(\01329.com.alipay.dds.api.v1.Datab"
  "aseAuthorities.VariablesEntry\022>\n\textensi"
  "on\030\004 \003(\0132+.com.alipay.dds.api.v1.MarkedM"
  "ultiReference\0320\n\016VariablesEntry\022\013\n\003key\030\001"
  " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\340\001\n\014DatabaseUser"
  "\022\014\n\004user\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\020\n\010password"
  "\030\003 \001(\t\022\023\n\013select_priv\030\004 \001(\t\022\023\n\013insert_pr"
  "iv\030\005 \001(\t\022\023\n\013update_priv\030\006 \001(\t\022\023\n\013delete_"
  "priv\030\007 \001(\t\022\023\n\013create_priv\030\010 \001(\t\022\021\n\tdrop_"
  "priv\030\t \001(\t\022\022\n\nindex_priv\030\n \001(\t\022\022\n\nalter_"
  "priv\030\013 \001(\tB\?\n\025com.alipay.dds.api.v1B\030Dat"
  "abaseAuthoritiesProtoP\000Z\ndds/api/v1b\006pro"
  "to3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_databaseAuthorities_2eproto = {
  false, InitDefaults_databaseAuthorities_2eproto, 
  descriptor_table_protodef_databaseAuthorities_2eproto,
  "databaseAuthorities.proto", &assign_descriptors_table_databaseAuthorities_2eproto, 683,
};

void AddDescriptors_databaseAuthorities_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_common_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_databaseAuthorities_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_databaseAuthorities_2eproto = []() { AddDescriptors_databaseAuthorities_2eproto(); return true; }();
namespace com {
namespace alipay {
namespace dds {
namespace api {
namespace v1 {

// ===================================================================

DatabaseAuthorities_VariablesEntry_DoNotUse::DatabaseAuthorities_VariablesEntry_DoNotUse() {}
DatabaseAuthorities_VariablesEntry_DoNotUse::DatabaseAuthorities_VariablesEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
void DatabaseAuthorities_VariablesEntry_DoNotUse::MergeFrom(const DatabaseAuthorities_VariablesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata DatabaseAuthorities_VariablesEntry_DoNotUse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_databaseAuthorities_2eproto);
  return ::file_level_metadata_databaseAuthorities_2eproto[0];
}
void DatabaseAuthorities_VariablesEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DatabaseAuthorities_VariablesEntry_DoNotUse::_ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx) {
  using MF = ::google::protobuf::internal::MapField<
      DatabaseAuthorities_VariablesEntry_DoNotUse, EntryKeyType, EntryValueType,
      kEntryKeyFieldType, kEntryValueFieldType,
      kEntryDefaultEnumValue>;
  auto mf = static_cast<MF*>(object);
  Parser<MF, ::google::protobuf::Map<EntryKeyType, EntryValueType>> parser(mf);
#define DO_(x) if (!(x)) return false
  DO_(parser.ParseMap(begin, end));
  DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
    parser.key().data(), static_cast<int>(parser.key().length()),
    ::google::protobuf::internal::WireFormatLite::PARSE,
    "com.alipay.dds.api.v1.DatabaseAuthorities.VariablesEntry.key"));
  DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
    parser.value().data(), static_cast<int>(parser.value().length()),
    ::google::protobuf::internal::WireFormatLite::PARSE,
    "com.alipay.dds.api.v1.DatabaseAuthorities.VariablesEntry.value"));
#undef DO_
  return true;
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER


// ===================================================================

void DatabaseAuthorities::InitAsDefaultInstance() {
  ::com::alipay::dds::api::v1::_DatabaseAuthorities_default_instance_._instance.get_mutable()->metadata_ = const_cast< ::com::alipay::dds::api::v1::MetaData*>(
      ::com::alipay::dds::api::v1::MetaData::internal_default_instance());
}
class DatabaseAuthorities::HasBitSetters {
 public:
  static const ::com::alipay::dds::api::v1::MetaData& metadata(const DatabaseAuthorities* msg);
};

const ::com::alipay::dds::api::v1::MetaData&
DatabaseAuthorities::HasBitSetters::metadata(const DatabaseAuthorities* msg) {
  return *msg->metadata_;
}
void DatabaseAuthorities::clear_metadata() {
  if (GetArenaNoVirtual() == nullptr && metadata_ != nullptr) {
    delete metadata_;
  }
  metadata_ = nullptr;
}
void DatabaseAuthorities::clear_extension() {
  extension_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DatabaseAuthorities::kMetadataFieldNumber;
const int DatabaseAuthorities::kUsersFieldNumber;
const int DatabaseAuthorities::kVariablesFieldNumber;
const int DatabaseAuthorities::kExtensionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DatabaseAuthorities::DatabaseAuthorities()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.alipay.dds.api.v1.DatabaseAuthorities)
}
DatabaseAuthorities::DatabaseAuthorities(const DatabaseAuthorities& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      users_(from.users_),
      extension_(from.extension_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  variables_.MergeFrom(from.variables_);
  if (from.has_metadata()) {
    metadata_ = new ::com::alipay::dds::api::v1::MetaData(*from.metadata_);
  } else {
    metadata_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:com.alipay.dds.api.v1.DatabaseAuthorities)
}

void DatabaseAuthorities::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_DatabaseAuthorities_databaseAuthorities_2eproto.base);
  metadata_ = nullptr;
}

DatabaseAuthorities::~DatabaseAuthorities() {
  // @@protoc_insertion_point(destructor:com.alipay.dds.api.v1.DatabaseAuthorities)
  SharedDtor();
}

void DatabaseAuthorities::SharedDtor() {
  if (this != internal_default_instance()) delete metadata_;
}

void DatabaseAuthorities::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DatabaseAuthorities& DatabaseAuthorities::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_DatabaseAuthorities_databaseAuthorities_2eproto.base);
  return *internal_default_instance();
}


void DatabaseAuthorities::Clear() {
// @@protoc_insertion_point(message_clear_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  users_.Clear();
  variables_.Clear();
  extension_.Clear();
  if (GetArenaNoVirtual() == nullptr && metadata_ != nullptr) {
    delete metadata_;
  }
  metadata_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DatabaseAuthorities::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<DatabaseAuthorities*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .com.alipay.dds.api.v1.MetaData metadata = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::com::alipay::dds::api::v1::MetaData::_InternalParse;
        object = msg->mutable_metadata();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // repeated .com.alipay.dds.api.v1.DatabaseUser users = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::com::alipay::dds::api::v1::DatabaseUser::_InternalParse;
          object = msg->add_users();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 18 && (ptr += 1));
        break;
      }
      // map<string, string> variables = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::SlowMapEntryParser;
          auto parse_map = ::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse::_ParseMap;
          ctx->extra_parse_data().payload.clear();
          ctx->extra_parse_data().parse_map = parse_map;
          object = &msg->variables_;
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(parse_map(ptr, newend, object, ctx));
          ptr = newend;
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 26 && (ptr += 1));
        break;
      }
      // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::com::alipay::dds::api::v1::MarkedMultiReference::_InternalParse;
          object = msg->add_extension();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 34 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DatabaseAuthorities::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .com.alipay.dds.api.v1.MetaData metadata = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_metadata()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .com.alipay.dds.api.v1.DatabaseUser users = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_users()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> variables = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DatabaseAuthorities_VariablesEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              DatabaseAuthorities_VariablesEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&variables_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseAuthorities.VariablesEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseAuthorities.VariablesEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_extension()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.alipay.dds.api.v1.DatabaseAuthorities)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.alipay.dds.api.v1.DatabaseAuthorities)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DatabaseAuthorities::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.alipay.dds.api.v1.MetaData metadata = 1;
  if (this->has_metadata()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::metadata(this), output);
  }

  // repeated .com.alipay.dds.api.v1.DatabaseUser users = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->users_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->users(static_cast<int>(i)),
      output);
  }

  // map<string, string> variables = 3;
  if (!this->variables().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "com.alipay.dds.api.v1.DatabaseAuthorities.VariablesEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "com.alipay.dds.api.v1.DatabaseAuthorities.VariablesEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->variables().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->variables().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->variables().begin();
          it != this->variables().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<DatabaseAuthorities_VariablesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(variables_.NewEntryWrapper(items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(3, *entry, output);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      ::std::unique_ptr<DatabaseAuthorities_VariablesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->variables().begin();
          it != this->variables().end(); ++it) {
        entry.reset(variables_.NewEntryWrapper(it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(3, *entry, output);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->extension_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->extension(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.alipay.dds.api.v1.DatabaseAuthorities)
}

::google::protobuf::uint8* DatabaseAuthorities::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.alipay.dds.api.v1.MetaData metadata = 1;
  if (this->has_metadata()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::metadata(this), target);
  }

  // repeated .com.alipay.dds.api.v1.DatabaseUser users = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->users_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->users(static_cast<int>(i)), target);
  }

  // map<string, string> variables = 3;
  if (!this->variables().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "com.alipay.dds.api.v1.DatabaseAuthorities.VariablesEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "com.alipay.dds.api.v1.DatabaseAuthorities.VariablesEntry.value");
      }
    };

    if (false &&
        this->variables().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->variables().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->variables().begin();
          it != this->variables().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<DatabaseAuthorities_VariablesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(variables_.NewEntryWrapper(items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageNoVirtualToArray(3, *entry, target);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      ::std::unique_ptr<DatabaseAuthorities_VariablesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->variables().begin();
          it != this->variables().end(); ++it) {
        entry.reset(variables_.NewEntryWrapper(it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageNoVirtualToArray(3, *entry, target);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->extension_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->extension(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.alipay.dds.api.v1.DatabaseAuthorities)
  return target;
}

size_t DatabaseAuthorities::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .com.alipay.dds.api.v1.DatabaseUser users = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->users_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->users(static_cast<int>(i)));
    }
  }

  // map<string, string> variables = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->variables_size());
  {
    ::std::unique_ptr<DatabaseAuthorities_VariablesEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->variables().begin();
        it != this->variables().end(); ++it) {
      entry.reset(variables_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // repeated .com.alipay.dds.api.v1.MarkedMultiReference extension = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->extension_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->extension(static_cast<int>(i)));
    }
  }

  // .com.alipay.dds.api.v1.MetaData metadata = 1;
  if (this->has_metadata()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *metadata_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DatabaseAuthorities::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  GOOGLE_DCHECK_NE(&from, this);
  const DatabaseAuthorities* source =
      ::google::protobuf::DynamicCastToGenerated<DatabaseAuthorities>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.alipay.dds.api.v1.DatabaseAuthorities)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.alipay.dds.api.v1.DatabaseAuthorities)
    MergeFrom(*source);
  }
}

void DatabaseAuthorities::MergeFrom(const DatabaseAuthorities& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  users_.MergeFrom(from.users_);
  variables_.MergeFrom(from.variables_);
  extension_.MergeFrom(from.extension_);
  if (from.has_metadata()) {
    mutable_metadata()->::com::alipay::dds::api::v1::MetaData::MergeFrom(from.metadata());
  }
}

void DatabaseAuthorities::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DatabaseAuthorities::CopyFrom(const DatabaseAuthorities& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.alipay.dds.api.v1.DatabaseAuthorities)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DatabaseAuthorities::IsInitialized() const {
  return true;
}

void DatabaseAuthorities::Swap(DatabaseAuthorities* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DatabaseAuthorities::InternalSwap(DatabaseAuthorities* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&users_)->InternalSwap(CastToBase(&other->users_));
  variables_.Swap(&other->variables_);
  CastToBase(&extension_)->InternalSwap(CastToBase(&other->extension_));
  swap(metadata_, other->metadata_);
}

::google::protobuf::Metadata DatabaseAuthorities::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_databaseAuthorities_2eproto);
  return ::file_level_metadata_databaseAuthorities_2eproto[kIndexInFileMessages];
}


// ===================================================================

void DatabaseUser::InitAsDefaultInstance() {
}
class DatabaseUser::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DatabaseUser::kUserFieldNumber;
const int DatabaseUser::kHostFieldNumber;
const int DatabaseUser::kPasswordFieldNumber;
const int DatabaseUser::kSelectPrivFieldNumber;
const int DatabaseUser::kInsertPrivFieldNumber;
const int DatabaseUser::kUpdatePrivFieldNumber;
const int DatabaseUser::kDeletePrivFieldNumber;
const int DatabaseUser::kCreatePrivFieldNumber;
const int DatabaseUser::kDropPrivFieldNumber;
const int DatabaseUser::kIndexPrivFieldNumber;
const int DatabaseUser::kAlterPrivFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DatabaseUser::DatabaseUser()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.alipay.dds.api.v1.DatabaseUser)
}
DatabaseUser::DatabaseUser(const DatabaseUser& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  user_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.user().size() > 0) {
    user_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_);
  }
  host_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.host().size() > 0) {
    host_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.host_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password().size() > 0) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  select_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.select_priv().size() > 0) {
    select_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.select_priv_);
  }
  insert_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.insert_priv().size() > 0) {
    insert_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.insert_priv_);
  }
  update_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.update_priv().size() > 0) {
    update_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.update_priv_);
  }
  delete_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.delete_priv().size() > 0) {
    delete_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.delete_priv_);
  }
  create_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.create_priv().size() > 0) {
    create_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.create_priv_);
  }
  drop_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.drop_priv().size() > 0) {
    drop_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.drop_priv_);
  }
  index_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.index_priv().size() > 0) {
    index_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.index_priv_);
  }
  alter_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.alter_priv().size() > 0) {
    alter_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.alter_priv_);
  }
  // @@protoc_insertion_point(copy_constructor:com.alipay.dds.api.v1.DatabaseUser)
}

void DatabaseUser::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_DatabaseUser_databaseAuthorities_2eproto.base);
  user_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  host_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  select_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  insert_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  update_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  delete_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  create_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  drop_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  index_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  alter_priv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

DatabaseUser::~DatabaseUser() {
  // @@protoc_insertion_point(destructor:com.alipay.dds.api.v1.DatabaseUser)
  SharedDtor();
}

void DatabaseUser::SharedDtor() {
  user_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  host_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  select_priv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  insert_priv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  update_priv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  delete_priv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  create_priv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  drop_priv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  index_priv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  alter_priv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DatabaseUser::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DatabaseUser& DatabaseUser::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_DatabaseUser_databaseAuthorities_2eproto.base);
  return *internal_default_instance();
}


void DatabaseUser::Clear() {
// @@protoc_insertion_point(message_clear_start:com.alipay.dds.api.v1.DatabaseUser)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  user_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  host_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  select_priv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  insert_priv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  update_priv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  delete_priv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  create_priv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  drop_priv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  index_priv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  alter_priv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DatabaseUser::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<DatabaseUser*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string user = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.user");
        object = msg->mutable_user();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string host = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.host");
        object = msg->mutable_host();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string password = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.password");
        object = msg->mutable_password();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string select_priv = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.select_priv");
        object = msg->mutable_select_priv();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string insert_priv = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 42) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.insert_priv");
        object = msg->mutable_insert_priv();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string update_priv = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 50) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.update_priv");
        object = msg->mutable_update_priv();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string delete_priv = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 58) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.delete_priv");
        object = msg->mutable_delete_priv();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string create_priv = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 66) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.create_priv");
        object = msg->mutable_create_priv();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string drop_priv = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 74) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.drop_priv");
        object = msg->mutable_drop_priv();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string index_priv = 10;
      case 10: {
        if (static_cast<::google::protobuf::uint8>(tag) != 82) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.index_priv");
        object = msg->mutable_index_priv();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string alter_priv = 11;
      case 11: {
        if (static_cast<::google::protobuf::uint8>(tag) != 90) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("com.alipay.dds.api.v1.DatabaseUser.alter_priv");
        object = msg->mutable_alter_priv();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DatabaseUser::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.alipay.dds.api.v1.DatabaseUser)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string user = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_user()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->user().data(), static_cast<int>(this->user().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.user"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string host = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_host()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->host().data(), static_cast<int>(this->host().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.host"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string password = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), static_cast<int>(this->password().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.password"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string select_priv = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_select_priv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->select_priv().data(), static_cast<int>(this->select_priv().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.select_priv"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string insert_priv = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (42 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_insert_priv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->insert_priv().data(), static_cast<int>(this->insert_priv().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.insert_priv"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string update_priv = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (50 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_update_priv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->update_priv().data(), static_cast<int>(this->update_priv().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.update_priv"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string delete_priv = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (58 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_delete_priv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->delete_priv().data(), static_cast<int>(this->delete_priv().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.delete_priv"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string create_priv = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (66 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_create_priv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->create_priv().data(), static_cast<int>(this->create_priv().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.create_priv"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string drop_priv = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (74 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_drop_priv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->drop_priv().data(), static_cast<int>(this->drop_priv().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.drop_priv"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string index_priv = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (82 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_index_priv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->index_priv().data(), static_cast<int>(this->index_priv().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.index_priv"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string alter_priv = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (90 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_alter_priv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->alter_priv().data(), static_cast<int>(this->alter_priv().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.alipay.dds.api.v1.DatabaseUser.alter_priv"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.alipay.dds.api.v1.DatabaseUser)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.alipay.dds.api.v1.DatabaseUser)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DatabaseUser::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.alipay.dds.api.v1.DatabaseUser)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string user = 1;
  if (this->user().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->user().data(), static_cast<int>(this->user().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.user");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->user(), output);
  }

  // string host = 2;
  if (this->host().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->host().data(), static_cast<int>(this->host().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.host");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->host(), output);
  }

  // string password = 3;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->password(), output);
  }

  // string select_priv = 4;
  if (this->select_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->select_priv().data(), static_cast<int>(this->select_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.select_priv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->select_priv(), output);
  }

  // string insert_priv = 5;
  if (this->insert_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->insert_priv().data(), static_cast<int>(this->insert_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.insert_priv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->insert_priv(), output);
  }

  // string update_priv = 6;
  if (this->update_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->update_priv().data(), static_cast<int>(this->update_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.update_priv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->update_priv(), output);
  }

  // string delete_priv = 7;
  if (this->delete_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->delete_priv().data(), static_cast<int>(this->delete_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.delete_priv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->delete_priv(), output);
  }

  // string create_priv = 8;
  if (this->create_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->create_priv().data(), static_cast<int>(this->create_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.create_priv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->create_priv(), output);
  }

  // string drop_priv = 9;
  if (this->drop_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->drop_priv().data(), static_cast<int>(this->drop_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.drop_priv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->drop_priv(), output);
  }

  // string index_priv = 10;
  if (this->index_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->index_priv().data(), static_cast<int>(this->index_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.index_priv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->index_priv(), output);
  }

  // string alter_priv = 11;
  if (this->alter_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->alter_priv().data(), static_cast<int>(this->alter_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.alter_priv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->alter_priv(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.alipay.dds.api.v1.DatabaseUser)
}

::google::protobuf::uint8* DatabaseUser::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.alipay.dds.api.v1.DatabaseUser)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string user = 1;
  if (this->user().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->user().data(), static_cast<int>(this->user().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.user");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->user(), target);
  }

  // string host = 2;
  if (this->host().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->host().data(), static_cast<int>(this->host().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.host");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->host(), target);
  }

  // string password = 3;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->password(), target);
  }

  // string select_priv = 4;
  if (this->select_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->select_priv().data(), static_cast<int>(this->select_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.select_priv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->select_priv(), target);
  }

  // string insert_priv = 5;
  if (this->insert_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->insert_priv().data(), static_cast<int>(this->insert_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.insert_priv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->insert_priv(), target);
  }

  // string update_priv = 6;
  if (this->update_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->update_priv().data(), static_cast<int>(this->update_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.update_priv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->update_priv(), target);
  }

  // string delete_priv = 7;
  if (this->delete_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->delete_priv().data(), static_cast<int>(this->delete_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.delete_priv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->delete_priv(), target);
  }

  // string create_priv = 8;
  if (this->create_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->create_priv().data(), static_cast<int>(this->create_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.create_priv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->create_priv(), target);
  }

  // string drop_priv = 9;
  if (this->drop_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->drop_priv().data(), static_cast<int>(this->drop_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.drop_priv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->drop_priv(), target);
  }

  // string index_priv = 10;
  if (this->index_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->index_priv().data(), static_cast<int>(this->index_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.index_priv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->index_priv(), target);
  }

  // string alter_priv = 11;
  if (this->alter_priv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->alter_priv().data(), static_cast<int>(this->alter_priv().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.alipay.dds.api.v1.DatabaseUser.alter_priv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->alter_priv(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.alipay.dds.api.v1.DatabaseUser)
  return target;
}

size_t DatabaseUser::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.alipay.dds.api.v1.DatabaseUser)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string user = 1;
  if (this->user().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->user());
  }

  // string host = 2;
  if (this->host().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->host());
  }

  // string password = 3;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  // string select_priv = 4;
  if (this->select_priv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->select_priv());
  }

  // string insert_priv = 5;
  if (this->insert_priv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->insert_priv());
  }

  // string update_priv = 6;
  if (this->update_priv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->update_priv());
  }

  // string delete_priv = 7;
  if (this->delete_priv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->delete_priv());
  }

  // string create_priv = 8;
  if (this->create_priv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->create_priv());
  }

  // string drop_priv = 9;
  if (this->drop_priv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->drop_priv());
  }

  // string index_priv = 10;
  if (this->index_priv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->index_priv());
  }

  // string alter_priv = 11;
  if (this->alter_priv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->alter_priv());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DatabaseUser::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.alipay.dds.api.v1.DatabaseUser)
  GOOGLE_DCHECK_NE(&from, this);
  const DatabaseUser* source =
      ::google::protobuf::DynamicCastToGenerated<DatabaseUser>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.alipay.dds.api.v1.DatabaseUser)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.alipay.dds.api.v1.DatabaseUser)
    MergeFrom(*source);
  }
}

void DatabaseUser::MergeFrom(const DatabaseUser& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.alipay.dds.api.v1.DatabaseUser)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.user().size() > 0) {

    user_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_);
  }
  if (from.host().size() > 0) {

    host_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.host_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  if (from.select_priv().size() > 0) {

    select_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.select_priv_);
  }
  if (from.insert_priv().size() > 0) {

    insert_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.insert_priv_);
  }
  if (from.update_priv().size() > 0) {

    update_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.update_priv_);
  }
  if (from.delete_priv().size() > 0) {

    delete_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.delete_priv_);
  }
  if (from.create_priv().size() > 0) {

    create_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.create_priv_);
  }
  if (from.drop_priv().size() > 0) {

    drop_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.drop_priv_);
  }
  if (from.index_priv().size() > 0) {

    index_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.index_priv_);
  }
  if (from.alter_priv().size() > 0) {

    alter_priv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.alter_priv_);
  }
}

void DatabaseUser::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.alipay.dds.api.v1.DatabaseUser)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DatabaseUser::CopyFrom(const DatabaseUser& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.alipay.dds.api.v1.DatabaseUser)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DatabaseUser::IsInitialized() const {
  return true;
}

void DatabaseUser::Swap(DatabaseUser* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DatabaseUser::InternalSwap(DatabaseUser* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  user_.Swap(&other->user_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  host_.Swap(&other->host_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_.Swap(&other->password_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  select_priv_.Swap(&other->select_priv_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  insert_priv_.Swap(&other->insert_priv_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  update_priv_.Swap(&other->update_priv_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  delete_priv_.Swap(&other->delete_priv_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  create_priv_.Swap(&other->create_priv_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  drop_priv_.Swap(&other->drop_priv_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  index_priv_.Swap(&other->index_priv_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  alter_priv_.Swap(&other->alter_priv_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata DatabaseUser::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_databaseAuthorities_2eproto);
  return ::file_level_metadata_databaseAuthorities_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
}  // namespace dds
}  // namespace alipay
}  // namespace com
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse* Arena::CreateMaybeMessage< ::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::com::alipay::dds::api::v1::DatabaseAuthorities_VariablesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::com::alipay::dds::api::v1::DatabaseAuthorities* Arena::CreateMaybeMessage< ::com::alipay::dds::api::v1::DatabaseAuthorities >(Arena* arena) {
  return Arena::CreateInternal< ::com::alipay::dds::api::v1::DatabaseAuthorities >(arena);
}
template<> PROTOBUF_NOINLINE ::com::alipay::dds::api::v1::DatabaseUser* Arena::CreateMaybeMessage< ::com::alipay::dds::api::v1::DatabaseUser >(Arena* arena) {
  return Arena::CreateInternal< ::com::alipay::dds::api::v1::DatabaseUser >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
