/**
 * Copyright (c) 2021 OceanBase
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef OBPROXY_LDC_STRUCT_H
#define OBPROXY_LDC_STRUCT_H
#include "lib/ob_errno.h"
#include "lib/ob_define.h"
#include "lib/string/ob_string.h"
#include "proxy/route/ob_route_enum.h"

namespace oceanbase
{
namespace obproxy
{
namespace proxy
{
enum ObIDCType
{
  SAME_IDC = 0,
  SAME_REGION,
  OTHER_REGION,
  MAX_IDC_TYPE,
};
const common::ObString get_idc_type_string(const ObIDCType type);

/*
 * |--- n bits  ---|----- 2bits -----|----- 2bits -----|--- 2 bits  ---|--- 2 bits  ---|--- 2 bits ---|--- 2 bits ---|--- 2 bits ---| LSB
 * | new attribute |  primary zone   |-- dup replica --|-- role type --|-- pl status --|  zone type   | merge status |     IDC      | LSB
 */
static const int64_t MERGE_BITS_SHIFT = 2;
static const int64_t ZONE_TYPE_BITS_SHIFT = 4;
static const int64_t PARTITION_BITS_SHIFT = 6;
static const int64_t ROLE_TYPE_BITS_SHIFT = 8;
static const int64_t DUP_REPLICA_BITS_SHIFT = 10;
static const int64_t PRIMARY_ZONE_BITS_SHIFT = 12;
static const int64_t NEW_ATTRIBUTE_BITS_SHIFT = 14;
static const int64_t IN_SAME_IDC = static_cast<int64_t>(SAME_IDC); //LOCAL
static const int64_t IN_SAME_REGION = static_cast<int64_t>(SAME_REGION); //REGION
static const int64_t IN_OTHER_REGION = static_cast<int64_t>(OTHER_REGION);//REMOTE
static const int64_t UNKNOWN_REGION = static_cast<int64_t>(MAX_IDC_TYPE);//UNKNOWN

static const int64_t IN_UNMERGING = 0 << MERGE_BITS_SHIFT; //UNMERGE
static const int64_t IN_MERGING = 1 << MERGE_BITS_SHIFT;//MERGE
static const int64_t UNKNOWN_MERGE_STATUS = 3 << MERGE_BITS_SHIFT;//UNKNOWN

static const int64_t IS_READWRITE_ZONE = 0 << ZONE_TYPE_BITS_SHIFT; //READWRITE
static const int64_t IS_READONLY_ZONE = 1 << ZONE_TYPE_BITS_SHIFT; //READONLY
static const int64_t UNKNOWN_ZONE_TYPE = 3 << ZONE_TYPE_BITS_SHIFT;//UNKNOWN

static const int64_t WITH_PARTITION_TYPE = 0 << PARTITION_BITS_SHIFT;//PARTITION
static const int64_t WITHOUT_PARTITION_TYPE = 1 << PARTITION_BITS_SHIFT;//NONPARTITION
static const int64_t UNKNOWN_PARTITION_TYPE = 3 << PARTITION_BITS_SHIFT;//UNKNOWN

static const int64_t IS_FOLLOWER = 0 << ROLE_TYPE_BITS_SHIFT; //FOLLOWER
static const int64_t IS_LEADER = 1 << ROLE_TYPE_BITS_SHIFT; //LEADER
static const int64_t UNKNOWN_ROLE = 3 << ROLE_TYPE_BITS_SHIFT;//UNKNOWN

static const int64_t NON_DUP_REPLICA = 0 << DUP_REPLICA_BITS_SHIFT; // NON DUP_REPLICA
static const int64_t IS_DUP_REPLICA = 1 << DUP_REPLICA_BITS_SHIFT; // IS DUP_REPLICA
static const int64_t UNKNOWN_DUP_REPLICA_TYPE = 3 << DUP_REPLICA_BITS_SHIFT; // UNKNOWN

static const int64_t NON_PRIMARY_ZONE = 0 << PRIMARY_ZONE_BITS_SHIFT; // USE NON PRIMARY ZONE
static const int64_t PRIMARY_ZONE = 1 << PRIMARY_ZONE_BITS_SHIFT; // USE PRIMARY ZONE
static const int64_t UNKNOWN_PRIMARY_ZONE = 2 << PRIMARY_ZONE_BITS_SHIFT; // UNKOWN

static const int64_t MAX_IDC_VALUE = ((1 << MERGE_BITS_SHIFT) -1);//0x0011
static const int64_t MAX_MERGE_VALUE = (((1 << (ZONE_TYPE_BITS_SHIFT - MERGE_BITS_SHIFT)) -1) << MERGE_BITS_SHIFT);//0x01100
static const int64_t MAX_ZONE_TYPE_VALUE = (((1 << (PARTITION_BITS_SHIFT - ZONE_TYPE_BITS_SHIFT)) -1) << ZONE_TYPE_BITS_SHIFT);//0x0011 0000
static const int64_t MAX_PARTITION_TYPE_VALUE = (((1 << (ROLE_TYPE_BITS_SHIFT - PARTITION_BITS_SHIFT)) -1) << PARTITION_BITS_SHIFT);//0x1100 0000
static const int64_t MAX_ROLE_TYPE_VALUE = (((1 << (DUP_REPLICA_BITS_SHIFT - ROLE_TYPE_BITS_SHIFT)) -1) << ROLE_TYPE_BITS_SHIFT);//0x0011 0000 0000
static const int64_t MAX_DUP_REPLICA_TYPE_VALUE = (((1 << (NEW_ATTRIBUTE_BITS_SHIFT - DUP_REPLICA_BITS_SHIFT)) -1) << DUP_REPLICA_BITS_SHIFT);//0x1100 0000 0000

enum ObRouteType
{
  ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_LOCAL  = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READWRITE_ZONE | IN_UNMERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 768
  ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_REGION = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READWRITE_ZONE | IN_UNMERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 769
  ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_REMOTE = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READWRITE_ZONE | IN_UNMERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 770
  ROUTE_TYPE_PARTITION_READWRITE_MERGE_LOCAL    = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READWRITE_ZONE | IN_MERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 772
  ROUTE_TYPE_PARTITION_READWRITE_MERGE_REGION   = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READWRITE_ZONE | IN_MERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 723
  ROUTE_TYPE_PARTITION_READWRITE_MERGE_REMOTE   = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READWRITE_ZONE | IN_MERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 724

  ROUTE_TYPE_PARTITION_READONLY_UNMERGE_LOCAL   = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READONLY_ZONE | IN_UNMERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 784
  ROUTE_TYPE_PARTITION_READONLY_UNMERGE_REGION  = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READONLY_ZONE | IN_UNMERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 785
  ROUTE_TYPE_PARTITION_READONLY_UNMERGE_REMOTE  = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READONLY_ZONE | IN_UNMERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 786
  ROUTE_TYPE_PARTITION_READONLY_MERGE_LOCAL     = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READONLY_ZONE | IN_MERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 788
  ROUTE_TYPE_PARTITION_READONLY_MERGE_REGION    = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READONLY_ZONE | IN_MERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 789
  ROUTE_TYPE_PARTITION_READONLY_MERGE_REMOTE    = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | IS_READONLY_ZONE | IN_MERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 790

  ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_LOCAL  = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READWRITE_ZONE | IN_UNMERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 832
  ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_REGION = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READWRITE_ZONE | IN_UNMERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 833
  ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_REMOTE = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READWRITE_ZONE | IN_UNMERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 834
  ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_LOCAL    = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READWRITE_ZONE | IN_MERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 836
  ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_REGION   = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READWRITE_ZONE | IN_MERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 837
  ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_REMOTE   = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READWRITE_ZONE | IN_MERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 838

  ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_LOCAL   = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READONLY_ZONE | IN_UNMERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 848
  ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_REGION  = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READONLY_ZONE | IN_UNMERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 849
  ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_REMOTE  = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READONLY_ZONE | IN_UNMERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 850
  ROUTE_TYPE_NONPARTITION_READONLY_MERGE_LOCAL     = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READONLY_ZONE | IN_MERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 852
  ROUTE_TYPE_NONPARTITION_READONLY_MERGE_REGION    = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READONLY_ZONE | IN_MERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 853
  ROUTE_TYPE_NONPARTITION_READONLY_MERGE_REMOTE    = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | IS_READONLY_ZONE | IN_MERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 854

  ROUTE_TYPE_PARTITION_UNMERGE_LOCAL  = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 816
  ROUTE_TYPE_PARTITION_UNMERGE_REGION = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 817
  ROUTE_TYPE_PARTITION_UNMERGE_REMOTE = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 818
  ROUTE_TYPE_PARTITION_MERGE_LOCAL    = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 820
  ROUTE_TYPE_PARTITION_MERGE_REGION   = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 821
  ROUTE_TYPE_PARTITION_MERGE_REMOTE   = (UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 822

  ROUTE_TYPE_NONPARTITION_UNMERGE_LOCAL  = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 880
  ROUTE_TYPE_NONPARTITION_UNMERGE_REGION = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 881
  ROUTE_TYPE_NONPARTITION_UNMERGE_REMOTE = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 882
  ROUTE_TYPE_NONPARTITION_MERGE_LOCAL    = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 884
  ROUTE_TYPE_NONPARTITION_MERGE_REGION   = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 885
  ROUTE_TYPE_NONPARTITION_MERGE_REMOTE   = (UNKNOWN_ROLE | WITHOUT_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 886

  ROUTE_TYPE_LEADER = (IS_LEADER | WITH_PARTITION_TYPE | MAX_ZONE_TYPE_VALUE | MAX_MERGE_VALUE | MAX_IDC_VALUE | MAX_DUP_REPLICA_TYPE_VALUE), // 319

  ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_LOCAL  = (IS_FOLLOWER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 48
  ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_REGION = (IS_FOLLOWER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 49
  ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_REMOTE = (IS_FOLLOWER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 50
  ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_LOCAL    = (IS_FOLLOWER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 52
  ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_REGION   = (IS_FOLLOWER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 53
  ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_REMOTE   = (IS_FOLLOWER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 54

  ROUTE_TYPE_LEADER_PARTITION_UNMERGE_LOCAL  = (IS_LEADER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 304
  ROUTE_TYPE_LEADER_PARTITION_UNMERGE_REGION = (IS_LEADER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 305
  ROUTE_TYPE_LEADER_PARTITION_UNMERGE_REMOTE = (IS_LEADER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 306
  ROUTE_TYPE_LEADER_PARTITION_MERGE_LOCAL    = (IS_LEADER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_IDC | UNKNOWN_DUP_REPLICA_TYPE), // 308
  ROUTE_TYPE_LEADER_PARTITION_MERGE_REGION   = (IS_LEADER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 309
  ROUTE_TYPE_LEADER_PARTITION_MERGE_REMOTE   = (IS_LEADER | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_OTHER_REGION | UNKNOWN_DUP_REPLICA_TYPE), // 310

  ROUTE_TYPE_DUP_PARTITION_UNMERGE_LOCAL = (IS_DUP_REPLICA | UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_IDC),
  ROUTE_TYPE_DUP_PARTITION_UNMERGE_REGION = (IS_DUP_REPLICA | UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_SAME_REGION),
  ROUTE_TYPE_DUP_PARTITION_MERGE_LOCAL = (IS_DUP_REPLICA | UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_IDC),
  ROUTE_TYPE_DUP_PARTITION_MERGE_REGION = (IS_DUP_REPLICA | UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_SAME_REGION),
  ROUTE_TYPE_DUP_PARTITION_UNMERGE_REMOTE = (IS_DUP_REPLICA | UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_UNMERGING | IN_OTHER_REGION),
  ROUTE_TYPE_DUP_PARTITION_MERGE_REMOTE = (IS_DUP_REPLICA | UNKNOWN_ROLE | WITH_PARTITION_TYPE | UNKNOWN_ZONE_TYPE | IN_MERGING | IN_OTHER_REGION),
  ROUTE_TYPE_PRIMARY_ZONE = PRIMARY_ZONE,

  ROUTE_TYPE_MAX = (MAX_ROLE_TYPE_VALUE | MAX_PARTITION_TYPE_VALUE | MAX_ZONE_TYPE_VALUE | MAX_MERGE_VALUE | MAX_IDC_VALUE | MAX_DUP_REPLICA_TYPE_VALUE),//16383
};
common::ObString get_route_type_string(const ObRouteType type);

class ObRouteTypeCheck
{
public:
  static bool is_route_type_valid(const int32_t route_type)
  {
    return (route_type >= 0 && route_type < ROUTE_TYPE_MAX);
  }
  static bool is_same_idc_type(const int32_t route_type)
  {
    return IN_SAME_IDC == (route_type & MAX_IDC_VALUE);
  }
  static bool is_same_region_type(const int32_t route_type)
  {
    return IN_SAME_REGION == (route_type & MAX_IDC_VALUE);
  }
  static bool is_other_region_type(const int32_t route_type)
  {
    return IN_OTHER_REGION == (route_type & MAX_IDC_VALUE);
  }
  static bool is_unmerge_type(const int32_t route_type)
  {
    return IN_UNMERGING == (route_type & MAX_MERGE_VALUE);
  }
  static bool is_merge_type(const int32_t route_type)
  {
    return IN_MERGING == (route_type & MAX_MERGE_VALUE);
  }
  static bool is_readonly_zone_type(const int32_t route_type)
  {
    return IS_READONLY_ZONE == (route_type & MAX_ZONE_TYPE_VALUE);
  }
  static bool is_readwrite_zone_type(const int32_t route_type)
  {
    return IS_READWRITE_ZONE == (route_type & MAX_ZONE_TYPE_VALUE);
  }
  static bool is_unknown_zone_type(const int32_t route_type)
  {
    return UNKNOWN_ZONE_TYPE == (route_type & MAX_ZONE_TYPE_VALUE);
  }
  static bool is_with_partition_type(const int32_t route_type)
  {
    return WITH_PARTITION_TYPE == (route_type & MAX_PARTITION_TYPE_VALUE);
  }
  static bool is_without_partition_type(const int32_t route_type)
  {
    return WITHOUT_PARTITION_TYPE == (route_type & MAX_PARTITION_TYPE_VALUE);
  }
  static bool is_leader_role(const int32_t route_type)
  {
    return IS_LEADER == (route_type & MAX_ROLE_TYPE_VALUE);
  }
  static bool is_follower_role(const int32_t route_type)
  {
    return IS_FOLLOWER == (route_type & MAX_ROLE_TYPE_VALUE);
  }
};


bool is_route_policy_enum_valid(const ObRoutePolicyEnum policy);




bool is_route_policy_enum_valid(const ObRoutePolicyEnum policy)
{
  return (MERGE_IDC_ORDER <= policy && policy < MAX_ROUTE_POLICY_COUNT);
}

inline bool is_target_replica_route(const ObRoutePolicyEnum policy)
{
  return TARGET_REPLICA_TYPE_WITH_LEADER == policy || TARGET_REPLICA_TYPE_FOLLOWER_FIRST == policy || TARGET_REPLICA_TYPE_FOLLOWER_ONLY == policy;
}

inline bool is_follower_only_route(const ObRoutePolicyEnum policy)
{
  return TARGET_REPLICA_TYPE_FOLLOWER_FIRST == policy
         || TARGET_REPLICA_TYPE_FOLLOWER_ONLY == policy
         || FOLLOWER_ONLY == policy
         || FOLLOWER_FIRST == policy;
}

inline bool is_weight_load_balance_route(const ObRoutePolicyEnum policy)
{
  return WEAKREAD_WEIGHT_LOAD_BALANCE == policy;
}

common::ObString get_route_type_string(const ObRouteType type)
{
  const char *str = "";
  switch (type) {
    case ROUTE_TYPE_PARTITION_READONLY_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_PARTITION_READONLY_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_PARTITION_READONLY_UNMERGE_REGION:
      str = "ROUTE_TYPE_PARTITION_READONLY_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_PARTITION_READONLY_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_PARTITION_READONLY_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_PARTITION_READONLY_MERGE_LOCAL:
      str = "ROUTE_TYPE_PARTITION_READONLY_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_PARTITION_READONLY_MERGE_REGION:
      str = "ROUTE_TYPE_PARTITION_READONLY_MERGE_REGION";
      break;
    case ROUTE_TYPE_PARTITION_READONLY_MERGE_REMOTE:
      str = "ROUTE_TYPE_PARTITION_READONLY_MERGE_REMOTE";
      break;
    case ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_REGION:
      str = "ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_PARTITION_READWRITE_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_PARTITION_READWRITE_MERGE_LOCAL:
      str = "ROUTE_TYPE_PARTITION_READWRITE_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_PARTITION_READWRITE_MERGE_REGION:
      str = "ROUTE_TYPE_PARTITION_READWRITE_MERGE_REGION";
      break;
    case ROUTE_TYPE_PARTITION_READWRITE_MERGE_REMOTE:
      str = "ROUTE_TYPE_PARTITION_READWRITE_MERGE_REMOTE";
      break;
    case ROUTE_TYPE_PARTITION_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_PARTITION_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_PARTITION_UNMERGE_REGION:
      str = "ROUTE_TYPE_PARTITION_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_PARTITION_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_PARTITION_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_PARTITION_MERGE_LOCAL:
      str = "ROUTE_TYPE_PARTITION_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_PARTITION_MERGE_REGION:
      str = "ROUTE_TYPE_PARTITION_MERGE_REGION";
      break;
    case ROUTE_TYPE_PARTITION_MERGE_REMOTE:
      str = "ROUTE_TYPE_PARTITION_MERGE_REMOTE";
      break;
    case ROUTE_TYPE_LEADER:
      str = "ROUTE_TYPE_LEADER";
      break;
    case ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_REGION:
      str = "ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_NONPARTITION_READONLY_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_NONPARTITION_READONLY_MERGE_LOCAL:
      str = "ROUTE_TYPE_NONPARTITION_READONLY_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_NONPARTITION_READONLY_MERGE_REGION:
      str = "ROUTE_TYPE_NONPARTITION_READONLY_MERGE_REGION";
      break;
    case ROUTE_TYPE_NONPARTITION_READONLY_MERGE_REMOTE:
      str = "ROUTE_TYPE_NONPARTITION_READONLY_MERGE_REMOTE";
      break;
    case ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_REGION:
      str = "ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_NONPARTITION_READWRITE_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_LOCAL:
      str = "ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_REGION:
      str = "ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_REGION";
      break;
    case ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_REMOTE:
      str = "ROUTE_TYPE_NONPARTITION_READWRITE_MERGE_REMOTE";
      break;
    case ROUTE_TYPE_NONPARTITION_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_NONPARTITION_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_NONPARTITION_UNMERGE_REGION:
      str = "ROUTE_TYPE_NONPARTITION_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_NONPARTITION_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_NONPARTITION_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_NONPARTITION_MERGE_LOCAL:
      str = "ROUTE_TYPE_NONPARTITION_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_NONPARTITION_MERGE_REGION:
      str = "ROUTE_TYPE_NONPARTITION_MERGE_REGION";
      break;
    case ROUTE_TYPE_NONPARTITION_MERGE_REMOTE:
      str = "ROUTE_TYPE_NONPARTITION_MERGE_REMOTE";
      break;
      // follower first
    case ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_REGION:
      str = "ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_FOLLOWER_PARTITION_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_LOCAL:
      str = "ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_REGION:
      str = "ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_REGION";
      break;
    case ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_REMOTE:
      str = "ROUTE_TYPE_FOLLOWER_PARTITION_MERGE_REMOTE";
      break;

    case ROUTE_TYPE_LEADER_PARTITION_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_LEADER_PARTITION_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_LEADER_PARTITION_UNMERGE_REGION:
      str = "ROUTE_TYPE_LEADER_PARTITION_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_LEADER_PARTITION_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_LEADER_PARTITION_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_LEADER_PARTITION_MERGE_LOCAL:
      str = "ROUTE_TYPE_LEADER_PARTITION_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_LEADER_PARTITION_MERGE_REGION:
      str = "ROUTE_TYPE_LEADER_PARTITION_MERGE_REGION";
      break;
    case ROUTE_TYPE_LEADER_PARTITION_MERGE_REMOTE:
      str = "ROUTE_TYPE_LEADER_PARTITION_MERGE_REMOTE";
      break;

    case ROUTE_TYPE_DUP_PARTITION_UNMERGE_LOCAL:
      str = "ROUTE_TYPE_DUP_PARTITION_UNMERGE_LOCAL";
      break;
    case ROUTE_TYPE_DUP_PARTITION_UNMERGE_REGION:
      str = "ROUTE_TYPE_DUP_PARTITION_UNMERGE_REGION";
      break;
    case ROUTE_TYPE_DUP_PARTITION_MERGE_LOCAL:
      str = "ROUTE_TYPE_DUP_PARTITION_MERGE_LOCAL";
      break;
    case ROUTE_TYPE_DUP_PARTITION_MERGE_REGION:
      str = "ROUTE_TYPE_DUP_PARTITION_MERGE_REGION";
      break;
    case ROUTE_TYPE_DUP_PARTITION_UNMERGE_REMOTE:
      str = "ROUTE_TYPE_DUP_PARTITION_UNMERGE_REMOTE";
      break;
    case ROUTE_TYPE_DUP_PARTITION_MERGE_REMOTE:
      str = "ROUTE_TYPE_DUP_PARTITION_MERGE_REMOTE";
      break;
    case ROUTE_TYPE_PRIMARY_ZONE:
      str = "ROUTE_TYPE_PRIMARY_ZONE";
      break;
    case ROUTE_TYPE_MAX:
      str = "ROUTE_TYPE_MAX";
      break;
    default:
      str = "ROUTE_TYPE_UNKNOWN";
  }
  return common::ObString::make_string(str);
}


const common::ObString get_idc_type_string(const ObIDCType type)
{
  static const common::ObString string_array[MAX_IDC_TYPE] =
  {
      common::ObString::make_string("SAME_IDC"),
      common::ObString::make_string("SAME_REGION"),
      common::ObString::make_string("OTHER_REGION"),
  };

  common::ObString string;
  if (OB_LIKELY(type >= SAME_IDC) && OB_LIKELY(type < MAX_IDC_TYPE)) {
    string = string_array[type];
  }
  return string;
}

enum ObProxyRoutePolicyEnum {
  FOLLOWER_FIRST_ENUM = 0,
  UNMERGE_FOLLOWER_FIRST_ENUM,
  FOLLOWER_ONLY_ENUM,
  TARGET_REPLICA_TYPE_WITH_LEADER_ENUM,
  Target_Replica_Type_Follower_First_ENUM,
  Target_Replica_Type_Follower_Only_ENUM,
  WEAKREAD_WEIGHT_LOAD_BALANCE_ENUM,
  MAX_PROXY_ROUTE_POLICY,
};

bool is_valid_proxy_route_policy(const ObProxyRoutePolicyEnum policy);
const common::ObString get_proxy_route_policy_enum_string(const ObRoutePolicyEnum policy);
ObProxyRoutePolicyEnum get_proxy_route_policy(const common::ObString &value);

bool is_valid_proxy_route_policy(const ObProxyRoutePolicyEnum policy)
{
  return policy >= FOLLOWER_FIRST_ENUM && policy < MAX_PROXY_ROUTE_POLICY;
}

const common::ObString get_proxy_route_policy_enum_string(const ObProxyRoutePolicyEnum policy)
{
  common::ObString string;
  static const common::ObString string_array[MAX_PROXY_ROUTE_POLICY] =
  {
      common::ObString::make_string("FOLLOWER_FIRST"),
      common::ObString::make_string("UNMERGE_FOLLOWER_FIRST"),
      common::ObString::make_string("FOLLOWER_ONLY"),
      common::ObString::make_string("TARGET_REPLICA_TYPE_WITH_LEADER"),
      common::ObString::make_string("TARGET_REPLICA_TYPE_FOLLOWER_FIRST"),
      common::ObString::make_string("TARGET_REPLICA_TYPE_FOLLOWER_ONLY"),
      common::ObString::make_string("WEAKREAD_WEIGHT_LOAD_BALANCE"),
  };

  if (OB_LIKELY(policy >= FOLLOWER_FIRST_ENUM)
      && OB_LIKELY(policy < MAX_PROXY_ROUTE_POLICY)) {
    string = string_array[policy];
  }
  return string;
}

ObProxyRoutePolicyEnum get_proxy_route_policy(const common::ObString &value)
{
  ObProxyRoutePolicyEnum ret_enum = MAX_PROXY_ROUTE_POLICY;
  if (!value.empty()) {
    for (int32_t i = 0; i < static_cast<int32_t>(MAX_PROXY_ROUTE_POLICY) && MAX_PROXY_ROUTE_POLICY == ret_enum; i++) {
      if (0 == get_proxy_route_policy_enum_string(static_cast<ObProxyRoutePolicyEnum>(i)).case_compare(value)) {
        ret_enum = static_cast<ObProxyRoutePolicyEnum>(i);
      }
    }
  }
  return ret_enum;
}
} // end of namespace proxy
} // end of namespace obproxy
} // end of namespace oceanbase

#endif /* OBPROXY_LDC_STRUCT_H */
