#line 2 "ob_expr_parser_utf8_lex.c"

#line 4 "ob_expr_parser_utf8_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ob_expr_parser_utf8_yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ob_expr_parser_utf8_yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void ob_expr_parser_utf8_yyrestart (FILE *input_file ,yyscan_t yyscanner );
void ob_expr_parser_utf8_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE ob_expr_parser_utf8_yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void ob_expr_parser_utf8_yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void ob_expr_parser_utf8_yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void ob_expr_parser_utf8_yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void ob_expr_parser_utf8_yypop_buffer_state (yyscan_t yyscanner );

static void ob_expr_parser_utf8_yyensure_buffer_stack (yyscan_t yyscanner );
static void ob_expr_parser_utf8_yy_load_buffer_state (yyscan_t yyscanner );
static void ob_expr_parser_utf8_yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER ob_expr_parser_utf8_yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE ob_expr_parser_utf8_yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE ob_expr_parser_utf8_yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE ob_expr_parser_utf8_yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *ob_expr_parser_utf8_yyalloc (yy_size_t ,yyscan_t yyscanner );
void *ob_expr_parser_utf8_yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void ob_expr_parser_utf8_yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer ob_expr_parser_utf8_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ob_expr_parser_utf8_yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ob_expr_parser_utf8_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ob_expr_parser_utf8_yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ob_expr_parser_utf8_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define ob_expr_parser_utf8_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[279] =
    {   0,
       34,   34,    0,    0,    0,    0,    0,    0,    0,    0,
       62,   60,   35,   35,   39,   50,   35,   34,   39,   39,
       44,   37,   38,   39,   36,   39,   39,   39,   32,   39,
       27,   22,   25,   29,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   56,   39,
       60,   60,   43,   42,   43,   45,   46,   61,   51,   52,
       61,   58,   59,   35,    0,   28,   35,   34,   15,   32,
        0,    0,   32,   33,   40,   33,   32,   34,    0,   30,
       26,   24,   34,    2,   34,   34,   34,   34,   18,   19,
       34,   34,   34,   34,   12,   16,   34,   34,   34,   34,

       34,   17,    0,    0,    0,   41,   45,    0,    0,   47,
        0,    0,   48,   51,    0,   53,    0,    0,    0,   54,
       58,   57,   32,   35,    0,   32,    0,    0,   33,    0,
       32,    0,   33,   30,   23,   14,   34,    6,   34,   34,
       34,   34,   21,   34,   34,    5,   34,   34,   34,   37,
       38,   36,   49,    0,   49,    0,    0,   55,    0,   55,
        0,    0,   32,   35,   35,   35,    0,   32,   33,    0,
       33,    0,   33,   32,   30,   34,   34,   34,   11,   34,
       20,   34,   34,   34,   34,    0,    0,    0,    0,   32,
       35,   32,   32,   30,   34,    8,   34,    7,   10,   34,

        4,    1,    0,    0,   49,    0,    0,    0,    0,   55,
        0,    0,   32,   32,   32,   30,   34,    9,   34,    3,
        0,    0,   32,   32,   32,   30,   13,   31,   32,   32,
       32,   30,   32,   32,   32,   30,   32,   32,   32,   30,
       32,   32,   32,   30,   32,   32,   32,   30,   32,   32,
       32,   30,   32,   32,   32,   30,   32,   32,   32,   30,
       32,   32,   32,   30,   32,   32,   32,   30,   32,   32,
       33,   30,   33,   33,   33,   33,   33,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,    9,   22,
       23,   24,   25,    9,   26,   27,    8,   28,   29,   30,
       31,   32,   33,   34,    8,   35,   36,   37,   38,   39,
        8,   40,   41,   42,   43,   44,   45,    8,   46,    8,
        1,   47,    1,    9,    8,   48,   49,   50,    8,   51,

       52,   53,   54,   55,   56,   57,    8,   58,   59,   60,
       61,   62,    8,   63,   64,   65,   66,   67,   68,    8,
       69,    8,    1,   70,    1,    9,    1,   71,    1,    1,
        1,    1,    1,    1,    1,   72,   73,    1,    1,   74,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   75,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   76,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   77,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[78] =
    {   0,
        1,    1,    2,    2,    1,    3,    1,    4,    1,    1,
        5,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    6,    7,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[295] =
    {   0,
        0,    0,   75,   76,   69,   70,   76,   77,  533,  532,
      579,  696,   82,   89,  555,  696,    0,    0,  696,  566,
      696,  696,  696,  555,  696,   77,  552,  557,   78,   84,
       64,  696,  547,  696,   65,   74,   67,   68,   83,   73,
       73,   79,   75,   82,   77,   98,   94,  107,  696,  499,
      496,  491,  696,  696,  132,    0,  152,    0,    0,  168,
        0,    0,  517,  145,  493,  696,    0,    0,  696,  543,
      174,  542,  161,  132,  696,  137,  162,  177,  541,  540,
      532,  696,  132,    0,  122,  133,  148,  144,    0,    0,
      160,  159,  157,  165,    0,    0,  156,  160,  162,  169,

      177,  696,  482,  158,  191,  696,    0,  231,  538,  696,
      530,  475,  696,    0,  234,  696,  538,  520,  465,  696,
        0,  696,  511,  243,  457,  223,  200,  234,  219,  238,
      239,  507,  502,  499,  696,    0,  211,    0,  217,  228,
      225,  230,    0,  229,  232,    0,  238,  224,  229,  696,
      696,  696,  696,  497,  492,  270,  424,  696,  485,  482,
      274,  416,  464,  204,  278,  290,  396,  277,  442,  437,
      435,  434,  433,  280,  430,  270,  262,  265,    0,  261,
        0,  276,  279,  279,  282,  310,  375,  314,  372,  422,
      332,  319,  320,  419,  301,    0,  302,    0,    0,  299,

      301,    0,  340,  355,  359,  364,  366,  370,  375,  379,
      385,  362,  406,  375,  376,  403,  332,    0,  355,    0,
      395,  405,  402,  392,  395,  399,    0,    0,  397,  396,
      400,  382,  381,  412,  416,  380,  377,  420,  440,  367,
      360,  441,  445,  340,  335,  453,  457,  332,  327,  460,
      461,  325,  303,  465,  478,  295,  276,  481,  482,  250,
      199,  486,  496,  192,  178,  500,  503,  148,  133,  506,
      521,  696,  120,  522,  525,  101,  539,  696,  591,  598,
      605,  612,  619,   96,  626,  633,  640,  647,  654,  660,
      667,  674,  681,  688

    } ;

static yyconst flex_int16_t yy_def[295] =
    {   0,
      278,    1,  279,  279,  280,  280,  281,  281,  282,  282,
      278,  278,  278,  278,  278,  278,  283,  284,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  284,  278,
      278,  278,  278,  278,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  278,  278,
      278,  278,  278,  278,  278,  285,  278,  286,  287,  278,
      288,  289,  278,  278,  278,  278,  283,  284,  278,  278,
      278,  278,  278,  278,  278,  278,  284,  284,  278,  278,
      278,  278,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  278,  278,  278,  278,  278,  285,  278,  290,  278,
      278,  278,  278,  287,  278,  278,  291,  278,  278,  278,
      289,  278,  278,  292,  278,  278,  278,  278,  278,  278,
      284,  278,  284,  278,  278,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  278,
      278,  278,  278,  290,  290,  278,  278,  278,  291,  291,
      278,  278,  278,  292,  292,  292,  278,  278,  278,  278,
      278,  278,  278,  284,  278,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  293,  278,  294,  278,  278,
      292,  278,  284,  278,  284,  284,  284,  284,  284,  284,

      284,  284,  293,  293,  293,  293,  278,  294,  294,  294,
      294,  278,  278,  278,  284,  278,  284,  284,  284,  284,
      293,  294,  278,  278,  284,  278,  284,  284,  278,  278,
      284,  278,  278,  278,  284,  278,  278,  278,  284,  278,
      278,  278,  284,  278,  278,  278,  284,  278,  278,  278,
      284,  278,  278,  278,  284,  278,  278,  278,  284,  278,
      278,  278,  284,  278,  278,  278,  284,  278,  278,  278,
      284,  278,  278,  278,  284,  278,  278,    0,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278

    } ;

static yyconst flex_int16_t yy_nxt[774] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   19,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   18,   18,   37,
       38,   39,   40,   41,   42,   18,   43,   44,   18,   45,
       46,   18,   18,   47,   48,   18,   12,   49,   35,   36,
       18,   18,   37,   38,   39,   40,   41,   42,   18,   43,
       44,   18,   45,   46,   18,   18,   47,   48,   18,   50,
       12,   12,   12,   12,   12,   51,   52,   54,   54,   57,
       57,   60,   60,   64,   64,   64,   81,   66,   55,   55,
       64,   64,   64,   71,   72,   76,   73,   77,   79,   68,

       79,   83,   85,   80,   86,   84,   78,   87,   88,   89,
       91,   92,   93,   90,   97,   58,   58,   94,   95,  100,
      276,   96,   61,   61,   83,   85,   98,   86,   84,   78,
       87,   88,   89,   91,   92,   93,   90,   97,  101,  276,
       94,   95,  100,   99,   96,  105,   64,   64,   64,   98,
      106,   74,  273,  108,  108,  108,  129,   65,  109,  136,
      128,  101,  110,  137,   65,  130,   99,  272,  111,  115,
      115,  115,  138,  116,  117,  124,  124,  124,   76,   76,
      126,  131,  136,  128,  118,  139,  137,  140,  130,  127,
       78,  132,  141,  132,  142,  138,  133,  269,  143,  144,

      145,  146,  147,  148,  105,  149,  278,  278,  139,  106,
      140,  268,  127,   78,  132,  141,  132,  142,  265,  169,
       65,  143,  144,  145,  146,  147,  148,  112,  149,  150,
      151,  152,  108,  108,  108,  115,  115,  115,  129,  158,
       76,  153,  168,  119,  165,  124,  124,  130,  170,  125,
      170,  127,  172,  171,  172,  176,   76,  173,  174,  177,
      178,  179,  180,  181,  182,  183,  184,   78,  185,  264,
      130,  186,  186,  186,  127,  188,  188,  188,  176,  165,
      124,  124,  177,  178,  179,  180,  181,  182,  183,  184,
       78,  185,  278,  278,   76,  261,  192,   76,  195,  193,

      196,  197,  198,  199,  200,  127,  112,  201,   78,  119,
      202,  204,  186,  186,  260,  209,  188,  188,  166,  210,
      205,  195,  257,  196,  197,  198,  199,  200,  127,  217,
      201,   78,  218,  202,  278,  278,   76,   76,  214,  215,
      219,  220,  278,  278,  256,  187,  253,  127,   78,  189,
      205,  252,  217,  166,  249,  218,  204,  186,  186,  248,
      191,  278,  278,  219,  220,  205,  278,  278,  227,  205,
      127,   78,  278,  278,  205,  210,  209,  188,  188,  245,
      210,  278,  278,  228,  210,  206,  244,  278,  278,  211,
      210,  227,   76,   76,  224,  225,  241,  278,  278,  240,

      237,  236,  165,  127,   78,  205,  228,  278,  278,   76,
      210,  230,   76,   76,  231,  234,  233,   76,  232,  235,
      127,  229,  226,   78,  127,  223,  127,   78,   78,   76,
      206,  238,  188,   76,  221,  239,  186,   76,  216,  242,
      127,  213,  212,  127,   78,  207,   78,  127,  127,  194,
      211,   78,  173,  173,  171,  222,  171,   76,   76,  243,
      246,  169,   76,  127,  247,  204,  124,   78,   78,  127,
       76,  127,  250,   78,   76,  209,  251,   76,   76,  254,
      255,  127,   76,  190,  258,   78,  115,  160,  127,   78,
      160,   78,  127,  127,  108,   76,   78,  259,   76,   76,

      262,  263,  155,   76,  127,  266,   78,  155,   78,  127,
       78,  127,   78,   76,  127,  267,  127,   76,  175,  270,
       76,  133,  271,   76,   78,  274,  169,  167,  127,   78,
      163,   78,  127,   78,  127,  162,  161,  127,   76,   76,
      275,  277,   76,  160,  275,  157,  156,   78,  155,   78,
      127,  127,   64,   78,   78,  135,   76,  127,  277,  134,
       80,   74,  123,  103,  122,  104,  103,  127,  102,   82,
       75,   74,   78,  127,   70,   69,   78,   66,  278,   63,
       63,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      127,   53,   53,   53,   53,   53,   53,   53,   56,   56,

       56,   56,   56,   56,   56,   59,   59,   59,   59,   59,
       59,   59,   62,   62,   62,   62,   62,   62,   62,   67,
      278,   67,   67,   67,   67,   67,  107,  107,  107,  107,
      278,  278,  107,  113,  113,  113,  113,  113,  113,  113,
      114,  114,  278,  114,  114,  278,  114,  120,  120,  120,
      120,  120,  120,  120,  121,  121,  121,  121,  121,  121,
      154,  278,  154,  154,  154,  154,  154,  159,  278,  159,
      159,  159,  159,  159,  164,  164,  164,  164,  164,  164,
      164,  203,  203,  203,  203,  203,  203,  203,  208,  208,
      208,  208,  208,  208,  208,   11,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278
    } ;

static yyconst flex_int16_t yy_chk[774] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    7,    8,   13,   13,   13,   31,   31,    3,    4,
       14,   14,   14,   26,   26,   29,   26,   29,   30,  284,

       30,   35,   36,   30,   37,   35,   29,   38,   39,   40,
       41,   42,   43,   40,   45,    5,    6,   43,   44,   47,
      276,   44,    7,    8,   35,   36,   46,   37,   35,   29,
       38,   39,   40,   41,   42,   43,   40,   45,   48,  273,
       43,   44,   47,   46,   44,   55,   64,   64,   64,   46,
       55,   74,  269,   57,   57,   57,   76,   13,   57,   83,
       74,   48,   57,   85,   14,   76,   46,  268,   57,   60,
       60,   60,   86,   60,   60,   71,   71,   71,   73,   77,
       73,   77,   83,   74,   60,   87,   85,   88,   76,   73,
       77,   78,   91,   78,   92,   86,   78,  265,   93,   94,

       97,   98,   99,  100,  105,  101,  164,  164,   87,  105,
       88,  264,   73,   77,  127,   91,  127,   92,  261,  127,
       64,   93,   94,   97,   98,   99,  100,   57,  101,  104,
      104,  104,  108,  108,  108,  115,  115,  115,  129,  115,
      126,  108,  126,   60,  124,  124,  124,  129,  128,   71,
      128,  126,  130,  128,  130,  137,  131,  130,  131,  139,
      140,  141,  142,  144,  145,  147,  148,  131,  149,  260,
      129,  156,  156,  156,  126,  161,  161,  161,  137,  165,
      165,  165,  139,  140,  141,  142,  144,  145,  147,  148,
      131,  149,  166,  166,  168,  257,  168,  174,  176,  174,

      177,  178,  180,  182,  183,  168,  108,  184,  174,  115,
      185,  186,  186,  186,  256,  188,  188,  188,  124,  188,
      186,  176,  253,  177,  178,  180,  182,  183,  168,  195,
      184,  174,  197,  185,  191,  191,  192,  193,  192,  193,
      200,  201,  203,  203,  252,  156,  249,  192,  193,  161,
      203,  248,  195,  165,  245,  197,  204,  204,  204,  244,
      166,  205,  205,  200,  201,  204,  206,  206,  217,  205,
      192,  193,  208,  208,  206,  208,  209,  209,  209,  241,
      209,  210,  210,  219,  210,  186,  240,  211,  211,  188,
      211,  217,  214,  215,  214,  215,  237,  221,  221,  236,

      233,  232,  191,  214,  215,  221,  219,  222,  222,  224,
      222,  224,  225,  230,  225,  230,  229,  231,  226,  231,
      224,  223,  216,  225,  230,  213,  214,  215,  231,  234,
      204,  234,  212,  235,  206,  235,  207,  238,  194,  238,
      234,  190,  189,  224,  235,  187,  225,  230,  238,  175,
      209,  231,  173,  172,  171,  211,  170,  239,  242,  239,
      242,  169,  243,  234,  243,  221,  167,  235,  239,  242,
      246,  238,  246,  243,  247,  222,  247,  250,  251,  250,
      251,  246,  254,  163,  254,  247,  162,  160,  250,  251,
      159,  239,  242,  254,  157,  255,  243,  255,  258,  259,

      258,  259,  155,  262,  246,  262,  255,  154,  247,  258,
      259,  250,  251,  263,  262,  263,  254,  266,  134,  266,
      267,  133,  267,  270,  263,  270,  132,  125,  266,  255,
      123,  267,  258,  259,  270,  119,  118,  262,  271,  274,
      271,  274,  275,  117,  275,  112,  111,  263,  109,  271,
      274,  266,  103,  275,  267,   81,  277,  270,  277,   80,
       79,   72,   70,   65,   63,   52,   51,  277,   50,   33,
       28,   27,  271,  274,   24,   20,  275,   15,   11,   10,
        9,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      277,  279,  279,  279,  279,  279,  279,  279,  280,  280,

      280,  280,  280,  280,  280,  281,  281,  281,  281,  281,
      281,  281,  282,  282,  282,  282,  282,  282,  282,  283,
        0,  283,  283,  283,  283,  283,  285,  285,  285,  285,
        0,    0,  285,  286,  286,  286,  286,  286,  286,  286,
      287,  287,    0,  287,  287,    0,  287,  288,  288,  288,
      288,  288,  288,  288,  289,  289,  289,  289,  289,  289,
      290,    0,  290,  290,  290,  290,  290,  291,    0,  291,
      291,  291,  291,  291,  292,  292,  292,  292,  292,  292,
      292,  293,  293,  293,  293,  293,  293,  293,  294,  294,
      294,  294,  294,  294,  294,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "ob_expr_parser_utf8.l"
#define YY_NO_INPUT 1
#line 7 "ob_expr_parser_utf8.l"
#define YYSTYPE         OBEXPRSTYPE
#define YYLTYPE         OBEXPRLTYPE
#include <stdlib.h>
#include "opsql/ob_proxy_parse_define.h"
#include "opsql/ob_proxy_parse_malloc.h"
#include "opsql/expr_parser/ob_expr_parse_result.h"
#include "opsql/expr_parser/ob_expr_parser_utf8_tab.h"
extern void ob_expr_utf8_parser_fatal_error(yyconst char *msg, yyscan_t yyscanner);

void store_expr_str(char* str, int64_t str_len, char* end_ptr, void *yyscanner);
void store_pos_place_holder(char* str, void *yyscanner);

#define YY_FATAL_ERROR(msg) ob_expr_utf8_parser_fatal_error(msg, yyscanner)

#define PUSH_STATE(state) \
  { yy_push_state(state, yyscanner); }

#define POP_STATE(state) \
  { yy_pop_state(yyscanner); }

#define RETURN_INT_VAL() \
do {\
  errno = 0;\
  yylval->num = strtoll(yytext, NULL, 10);\
  if (0 != errno) {\
      yylval->num = 0;\
  }\
  return INT_VAL;\
} while (0);

#define RETURN_STR_VAL() \
  { store_expr_str(yytext, yyleng, yytext + yyleng, yyscanner); return STR_VAL; }

#define RETURN_NUMBER_VAL() \
  { store_expr_str(yytext, yyleng, yytext + yyleng, yyscanner); return STR_VAL; }

#define RETURN_NAME_OB() \
  { store_expr_str(yytext, yyleng, yytext + yyleng, yyscanner); return NAME_OB; }

#define RETURN_ROW_ID() \
  { store_expr_str(yytext, yyleng, yytext + yyleng, yyscanner); return ROW_ID; }

#define RETURN_REVERSED_EXPR_FUNC() \
  { store_expr_str(yytext, yyleng, yytext + yyleng, yyscanner); return REVERSED_EXPR_FUNC; }





/*following character status will be rewrite by gen_parse.sh according to connection character*/
/* limit the length of int_num from 1 to 17 in case of int64_t out of bound, 17 -> [ ( length of 2^64 ) - 2 ]*/
#line 753 "ob_expr_parser_utf8_lex.c"

#define INITIAL 0
#define in_c_comment 1
#define sq 2
#define dq 3
#define bt 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int ob_expr_parser_utf8_yylex_init (yyscan_t* scanner);

int ob_expr_parser_utf8_yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ob_expr_parser_utf8_yylex_destroy (yyscan_t yyscanner );

int ob_expr_parser_utf8_yyget_debug (yyscan_t yyscanner );

void ob_expr_parser_utf8_yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE ob_expr_parser_utf8_yyget_extra (yyscan_t yyscanner );

void ob_expr_parser_utf8_yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *ob_expr_parser_utf8_yyget_in (yyscan_t yyscanner );

void ob_expr_parser_utf8_yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *ob_expr_parser_utf8_yyget_out (yyscan_t yyscanner );

void ob_expr_parser_utf8_yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int ob_expr_parser_utf8_yyget_leng (yyscan_t yyscanner );

char *ob_expr_parser_utf8_yyget_text (yyscan_t yyscanner );

int ob_expr_parser_utf8_yyget_lineno (yyscan_t yyscanner );

void ob_expr_parser_utf8_yyset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * ob_expr_parser_utf8_yyget_lval (yyscan_t yyscanner );

void ob_expr_parser_utf8_yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *ob_expr_parser_utf8_yyget_lloc (yyscan_t yyscanner );
    
        void ob_expr_parser_utf8_yyset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ob_expr_parser_utf8_yywrap (yyscan_t yyscanner );
#else
extern int ob_expr_parser_utf8_yywrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

    static void yy_push_state (int new_state ,yyscan_t yyscanner);
    
    static void yy_pop_state (yyscan_t yyscanner );
    
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ob_expr_parser_utf8_yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int ob_expr_parser_utf8_yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 102 "ob_expr_parser_utf8.l"

#line 1004 "ob_expr_parser_utf8_lex.c"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ob_expr_parser_utf8_yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				ob_expr_parser_utf8_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		ob_expr_parser_utf8_yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 696 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 103 "ob_expr_parser_utf8.l"
{ return WHERE; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 104 "ob_expr_parser_utf8.l"
{ return AS; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 105 "ob_expr_parser_utf8.l"
{ return VALUES; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 106 "ob_expr_parser_utf8.l"
{ return VALUES; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 107 "ob_expr_parser_utf8.l"
{ return SET; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 108 "ob_expr_parser_utf8.l"
{ return END_WHERE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "ob_expr_parser_utf8.l"
{ return END_WHERE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 110 "ob_expr_parser_utf8.l"
{ return END_WHERE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 111 "ob_expr_parser_utf8.l"
{ return END_WHERE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 112 "ob_expr_parser_utf8.l"
{ RETURN_ROW_ID(); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 114 "ob_expr_parser_utf8.l"
{ return JOIN; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 "ob_expr_parser_utf8.l"
{ return ON; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 116 "ob_expr_parser_utf8.l"
{ return BETWEEN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "ob_expr_parser_utf8.l"
{ return AND_OP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "ob_expr_parser_utf8.l"
{ return AND_OP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "ob_expr_parser_utf8.l"
{ return OR_OP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "ob_expr_parser_utf8.l"
{ return OR_OP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "ob_expr_parser_utf8.l"
{ return IN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 122 "ob_expr_parser_utf8.l"
{ return IS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "ob_expr_parser_utf8.l"
{ return TOKEN_NULL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 124 "ob_expr_parser_utf8.l"
{ return NOT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 125 "ob_expr_parser_utf8.l"
{ return COMP_EQ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 126 "ob_expr_parser_utf8.l"
{ return COMP_NSEQ; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 127 "ob_expr_parser_utf8.l"
{ return COMP_GE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "ob_expr_parser_utf8.l"
{ return COMP_GT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 129 "ob_expr_parser_utf8.l"
{ return COMP_LE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 130 "ob_expr_parser_utf8.l"
{ return COMP_LT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 131 "ob_expr_parser_utf8.l"
{ return COMP_NE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "ob_expr_parser_utf8.l"
{ return PLACE_HOLDER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "ob_expr_parser_utf8.l"
{ store_pos_place_holder(yytext + 1, yyscanner); return POS_PLACE_HOLDER; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "ob_expr_parser_utf8.l"
{ RETURN_REVERSED_EXPR_FUNC();}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 136 "ob_expr_parser_utf8.l"
{ RETURN_INT_VAL(); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 137 "ob_expr_parser_utf8.l"
{ RETURN_NUMBER_VAL(); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "ob_expr_parser_utf8.l"
{ RETURN_NAME_OB(); }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 139 "ob_expr_parser_utf8.l"
{ }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 140 "ob_expr_parser_utf8.l"
{ return ','; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "ob_expr_parser_utf8.l"
{ return '('; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "ob_expr_parser_utf8.l"
{ return ')'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "ob_expr_parser_utf8.l"
{ return yytext[0]; }
	YY_BREAK
/* comment */
case 40:
YY_RULE_SETUP
#line 146 "ob_expr_parser_utf8.l"
{ PUSH_STATE(in_c_comment); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 147 "ob_expr_parser_utf8.l"
{ POP_STATE(); }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 148 "ob_expr_parser_utf8.l"
{}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 149 "ob_expr_parser_utf8.l"
{}
	YY_BREAK
/* quote */
case 44:
YY_RULE_SETUP
#line 152 "ob_expr_parser_utf8.l"
{
  PUSH_STATE(sq);
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (OB_NOTNULL(p)) {
    p->tmp_buf_ = (yytext + 1);
    p->tmp_start_ptr_ = yytext;
    p->tmp_len_ = 0;
  }
}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 162 "ob_expr_parser_utf8.l"
{
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (OB_NOTNULL(p)) {
    p->tmp_len_ += yyleng;
  }
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 169 "ob_expr_parser_utf8.l"
{
  POP_STATE();
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (OB_NOTNULL(p)) {
    store_expr_str(p->tmp_buf_, p->tmp_len_, p->tmp_start_ptr_ + p->tmp_len_ + 2, yyscanner);
  }
  return STR_VAL;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 178 "ob_expr_parser_utf8.l"
{}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 179 "ob_expr_parser_utf8.l"
{
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (OB_NOTNULL(p)) {
    p->tmp_len_ += yyleng;
  }
}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 185 "ob_expr_parser_utf8.l"
{}
	YY_BREAK
case YY_STATE_EOF(sq):
#line 186 "ob_expr_parser_utf8.l"
{ return ERROR; }
	YY_BREAK
/* dquote */
case 50:
YY_RULE_SETUP
#line 190 "ob_expr_parser_utf8.l"
{
  PUSH_STATE(dq);
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (OB_NOTNULL(p)) {
    p->tmp_buf_ = (yytext + 1);
    p->tmp_start_ptr_ = yytext;
    p->tmp_len_ = 0;
  }
}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 200 "ob_expr_parser_utf8.l"
{
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (OB_NOTNULL(p)) {
    p->tmp_len_ += yyleng;
  }
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 207 "ob_expr_parser_utf8.l"
{
  POP_STATE();
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (OB_NOTNULL(p)) {
    store_expr_str(p->tmp_buf_, p->tmp_len_, p->tmp_start_ptr_ + p->tmp_len_ + 2, yyscanner);
    if (p->is_oracle_mode_) {
      return NAME_OB;
    }
  }
  return STR_VAL;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 219 "ob_expr_parser_utf8.l"
{}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 220 "ob_expr_parser_utf8.l"
{}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 221 "ob_expr_parser_utf8.l"
{}
	YY_BREAK
case YY_STATE_EOF(dq):
#line 222 "ob_expr_parser_utf8.l"
{ return ERROR; }
	YY_BREAK
/* backtick */
case 56:
YY_RULE_SETUP
#line 226 "ob_expr_parser_utf8.l"
{
  PUSH_STATE(bt);
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (NULL != p) {
    p->tmp_buf_ = (char *)obproxy_parse_malloc(OBPROXY_MAX_NAME_LENGTH, p->malloc_pool_);
    p->tmp_start_ptr_ = yytext;
    p->tmp_len_ = 0;
  }
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 236 "ob_expr_parser_utf8.l"
{
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (NULL != p && NULL != p->tmp_buf_ && p->tmp_len_ + 1 < OBPROXY_MAX_NAME_LENGTH) {
    p->tmp_buf_[p->tmp_len_++] = '`';
  }
}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 243 "ob_expr_parser_utf8.l"
{
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (NULL != p && NULL != p->tmp_buf_ && p->tmp_len_ + yyleng < OBPROXY_MAX_NAME_LENGTH) {
    memcpy(p->tmp_buf_ + p->tmp_len_, yytext, yyleng);
    p->tmp_len_ += yyleng;
  }
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 251 "ob_expr_parser_utf8.l"
{
  POP_STATE();
  ObExprParseResult *p = (ObExprParseResult *)yyextra;
  if (NULL != p && NULL != p->tmp_buf_) {
    yylval->str.str_  = obproxy_parse_strndup(p->tmp_buf_, p->tmp_len_, p->malloc_pool_);
    yylval->str.str_len_ = p->tmp_len_;
    yylval->str.end_ptr_ = p->tmp_start_ptr_ + p->tmp_len_ + 2;
  }
  return NAME_OB;
}
	YY_BREAK
case YY_STATE_EOF(bt):
#line 262 "ob_expr_parser_utf8.l"
{
  return ERROR;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(in_c_comment):
#line 266 "ob_expr_parser_utf8.l"
{ return END_P; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 267 "ob_expr_parser_utf8.l"
{ return IGNORED_WORD; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 268 "ob_expr_parser_utf8.l"
ECHO;
	YY_BREAK
#line 1504 "ob_expr_parser_utf8_lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * ob_expr_parser_utf8_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( ob_expr_parser_utf8_yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of ob_expr_parser_utf8_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ob_expr_parser_utf8_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ob_expr_parser_utf8_yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ob_expr_parser_utf8_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 278);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ob_expr_parser_utf8_yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ob_expr_parser_utf8_yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ob_expr_parser_utf8_yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        ob_expr_parser_utf8_yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            ob_expr_parser_utf8_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	ob_expr_parser_utf8_yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	ob_expr_parser_utf8_yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void ob_expr_parser_utf8_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ob_expr_parser_utf8_yypop_buffer_state();
	 *		ob_expr_parser_utf8_yypush_buffer_state(new_buffer);
     */
	ob_expr_parser_utf8_yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ob_expr_parser_utf8_yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (ob_expr_parser_utf8_yywrap()) processing, but the only time this flag
	 * is looked at is after ob_expr_parser_utf8_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void ob_expr_parser_utf8_yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ob_expr_parser_utf8_yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ob_expr_parser_utf8_yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ob_expr_parser_utf8_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ob_expr_parser_utf8_yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ob_expr_parser_utf8_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ob_expr_parser_utf8_yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ob_expr_parser_utf8_yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void ob_expr_parser_utf8_yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ob_expr_parser_utf8_yyfree((void *) b->yy_ch_buf ,yyscanner );

	ob_expr_parser_utf8_yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ob_expr_parser_utf8_yyrestart() or at EOF.
 */
    static void ob_expr_parser_utf8_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	ob_expr_parser_utf8_yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ob_expr_parser_utf8_yy_init_buffer was _probably_
     * called from ob_expr_parser_utf8_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void ob_expr_parser_utf8_yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ob_expr_parser_utf8_yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void ob_expr_parser_utf8_yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	ob_expr_parser_utf8_yyensure_buffer_stack(yyscanner);

	/* This block is copied from ob_expr_parser_utf8_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ob_expr_parser_utf8_yy_switch_to_buffer. */
	ob_expr_parser_utf8_yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void ob_expr_parser_utf8_yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	ob_expr_parser_utf8_yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		ob_expr_parser_utf8_yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ob_expr_parser_utf8_yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)ob_expr_parser_utf8_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in ob_expr_parser_utf8_yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)ob_expr_parser_utf8_yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in ob_expr_parser_utf8_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ob_expr_parser_utf8_yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ob_expr_parser_utf8_yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ob_expr_parser_utf8_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ob_expr_parser_utf8_yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ob_expr_parser_utf8_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ob_expr_parser_utf8_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE ob_expr_parser_utf8_yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return ob_expr_parser_utf8_yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to ob_expr_parser_utf8_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ob_expr_parser_utf8_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ob_expr_parser_utf8_yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ob_expr_parser_utf8_yy_scan_bytes()" );

	memcpy(buf, yybytes, _yybytes_len);

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ob_expr_parser_utf8_yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ob_expr_parser_utf8_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
		{
		yy_size_t new_size;

		yyg->yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yyg->yy_start_stack_depth * sizeof( int );

		if ( ! yyg->yy_start_stack )
			yyg->yy_start_stack = (int *) ob_expr_parser_utf8_yyalloc(new_size ,yyscanner );

		else
			yyg->yy_start_stack = (int *) ob_expr_parser_utf8_yyrealloc((void *) yyg->yy_start_stack,new_size ,yyscanner );

		if ( ! yyg->yy_start_stack )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( --yyg->yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
}


#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE ob_expr_parser_utf8_yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int ob_expr_parser_utf8_yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int ob_expr_parser_utf8_yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *ob_expr_parser_utf8_yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *ob_expr_parser_utf8_yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int ob_expr_parser_utf8_yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *ob_expr_parser_utf8_yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void ob_expr_parser_utf8_yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void ob_expr_parser_utf8_yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "ob_expr_parser_utf8_yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void ob_expr_parser_utf8_yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "ob_expr_parser_utf8_yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see ob_expr_parser_utf8_yy_switch_to_buffer
 */
void ob_expr_parser_utf8_yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void ob_expr_parser_utf8_yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int ob_expr_parser_utf8_yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void ob_expr_parser_utf8_yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * ob_expr_parser_utf8_yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void ob_expr_parser_utf8_yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *ob_expr_parser_utf8_yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void ob_expr_parser_utf8_yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* ob_expr_parser_utf8_yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int ob_expr_parser_utf8_yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) ob_expr_parser_utf8_yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* ob_expr_parser_utf8_yylex_init_extra has the same functionality as ob_expr_parser_utf8_yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to ob_expr_parser_utf8_yyalloc in
 * the yyextra field.
 */

int ob_expr_parser_utf8_yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    ob_expr_parser_utf8_yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) ob_expr_parser_utf8_yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    ob_expr_parser_utf8_yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ob_expr_parser_utf8_yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ob_expr_parser_utf8_yylex_init()
     */
    return 0;
}

/* ob_expr_parser_utf8_yylex_destroy is for both reentrant and non-reentrant scanners. */
int ob_expr_parser_utf8_yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ob_expr_parser_utf8_yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ob_expr_parser_utf8_yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	ob_expr_parser_utf8_yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        ob_expr_parser_utf8_yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ob_expr_parser_utf8_yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    ob_expr_parser_utf8_yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 268 "ob_expr_parser_utf8.l"



inline void *ob_expr_parser_utf8_yyalloc(size_t bytes,void *yyscanner)
{
  void *ptr_ret = NULL;
  ObExprParseResult *p = ob_expr_parser_utf8_yyget_extra(yyscanner);
  if (OB_ISNULL(p)) {
    // print err into msg buffer later
  } else {
    ptr_ret = obproxy_parse_malloc(bytes, p->malloc_pool_);
  }
  return ptr_ret;
}

inline void *ob_expr_parser_utf8_yyrealloc(void *ptr,size_t bytes,void *yyscanner)
{
  void *ptr_ret = NULL;
  ObExprParseResult *p = ob_expr_parser_utf8_yyget_extra(yyscanner);
  if (OB_ISNULL(p)) {
    // print err into msg buffer later
  } else {
    ptr_ret = obproxy_parse_realloc(ptr, bytes, p->malloc_pool_);
  }
  return ptr_ret;

}

inline void ob_expr_parser_utf8_yyfree(void *ptr,void *yyscanner)
{
  // Do nothing -- we leave it to the garbage collector.
  obproxy_parse_free(ptr);
}

inline void store_expr_str(char* str, int64_t str_len, char*end_ptr, void *yyscanner)
{
  YYSTYPE *lval = ob_expr_parser_utf8_yyget_lval(yyscanner);
  if (OB_ISNULL(lval)) {
    // do nothing
  } else {
    lval->str.str_ = str;
    lval->str.end_ptr_ = end_ptr;
    lval->str.str_len_ = str_len;
  }
}

inline void store_pos_place_holder(char *str, void *yyscanner)
{
  YYSTYPE *lval = ob_expr_parser_utf8_yyget_lval(yyscanner);
  if (OB_ISNULL(lval)) {
    // do nothing
  } else {
    errno = 0;
    lval->num = strtoll(str, NULL, 10);
    if (0 != errno) {
      lval->num = 0;
    }
  }
}

/* A Bison parser, made by GNU Bison 2.4.1.  */

/* Skeleton interface for Bison's Yacc-like parsers in C
   
      Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.
   
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.
   
   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */


#ifndef YY_OBEXPR_OB_EXPR_PARSER_TAB_H_INCLUDED
# define YY_OBEXPR_OB_EXPR_PARSER_TAB_H_INCLUDED
/* Debug traces.  */
#ifndef OBEXPR_UTF8_DEBUG
# if defined YYDEBUG
#if YYDEBUG
#   define OBEXPR_UTF8_DEBUG 1
#  else
#   define OBEXPR_UTF8_DEBUG 0
#  endif
# else /* ! defined YYDEBUG */
#  define OBEXPR_UTF8_DEBUG 0
# endif /* ! defined YYDEBUG */
#endif  /* ! defined OBEXPR_UTF8_DEBUG */
#if OBEXPR_UTF8_DEBUG
extern int ob_expr_parser_utf8_yydebug;
#endif
/* Tokens.  */
#ifndef OBEXPRTOKENTYPE
# define OBEXPRTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum obexprtokentype {
     DUMMY_SELECT_CLAUSE = 258,
     DUMMY_INSERT_CLAUSE = 259,
     WHERE = 260,
     AS = 261,
     VALUES = 262,
     SET = 263,
     END_WHERE = 264,
     JOIN = 265,
     AND_OP = 266,
     OR_OP = 267,
     IN = 268,
     ON = 269,
     BETWEEN = 270,
     IS = 271,
     TOKEN_NULL = 272,
     NOT = 273,
     COMP_EQ = 274,
     COMP_NSEQ = 275,
     COMP_GE = 276,
     COMP_GT = 277,
     COMP_LE = 278,
     COMP_LT = 279,
     COMP_NE = 280,
     PLACE_HOLDER = 281,
     END_P = 282,
     ERROR = 283,
     IGNORED_WORD = 284,
     NAME_OB = 285,
     STR_VAL = 286,
     ROW_ID = 287,
     REVERSED_EXPR_FUNC = 288,
     INT_VAL = 289,
     POS_PLACE_HOLDER = 290
   };
#endif



#if ! defined OBEXPRSTYPE && ! defined OBEXPRSTYPE_IS_DECLARED
typedef union OBEXPRSTYPE
{


  int64_t              num;
  ObProxyParseString   str;
  ObProxyFunctionType  func;
  ObProxyOperatorType  operator;
  ObProxyTokenNode     *node;
  ObProxyTokenList     *list;
  ObProxyRelationExpr  *relation;



} OBEXPRSTYPE;
# define OBEXPRSTYPE_IS_TRIVIAL 1
# define obexprstype OBEXPRSTYPE /* obsolescent; will be withdrawn */
# define OBEXPRSTYPE_IS_DECLARED 1
#endif



#if ! defined OBEXPRLTYPE && ! defined OBEXPRLTYPE_IS_DECLARED
typedef struct OBEXPRLTYPE
{
  int first_line;
  int first_column;
  int last_line;
  int last_column;
} OBEXPRLTYPE;
# define obexprltype OBEXPRLTYPE /* obsolescent; will be withdrawn */
# define OBEXPRLTYPE_IS_DECLARED 1
# define OBEXPRLTYPE_IS_TRIVIAL 1
#endif



#endif

